#!/bin/bash

set -euo pipefail

libxc_lib="${EBROOTLIBXC}/lib"
libxc_inc="${EBROOTLIBXC}/include"
workdir=$(mktemp -d "${TMPDIR:-/tmp}/libxc-fortran-check.XXXXXX")
trap 'rm -rf "${workdir}"' EXIT

echo "=== compiler ==="
command -v ifx
ifx --version | head -n 1

echo
echo "=== installed files ==="
ls -l "${libxc_inc}/xc_f03_lib_m.mod"
ls -l "${libxc_lib}/libxcf03.so"

echo
echo "=== compiler recorded in libxcf03.so ==="
readelf --string-dump=.comment "${libxc_lib}/libxcf03.so" 2>/dev/null || true

echo
echo "=== symbol exported by libxcf03.so ==="
nm -D --defined-only "${libxc_lib}/libxcf03.so" |
    grep 'xc_f03_lib_m.*xc_f03_version' || true

cd "${workdir}"

cat > compiler_probe.f90 <<'EOF'
module compiler_probe_m
contains
subroutine compiler_probe()
end subroutine compiler_probe
end module compiler_probe_m
EOF

ifx -c compiler_probe.f90

echo
echo "=== module symbol generated by the current ifx ==="
nm --defined-only compiler_probe.o | grep -i compiler_probe || true

cat > libxc_probe.f90 <<'EOF'
program libxc_probe
    use xc_f03_lib_m, only: xc_f03_version
    implicit none

    integer :: major, minor, micro

    call xc_f03_version(major, minor, micro)
    write(*, '(3(I0,1X))') major, minor, micro
end program libxc_probe
EOF

ifx -I"${libxc_inc}" -c libxc_probe.f90

echo
echo "=== symbol requested through the installed .mod file ==="
nm --undefined-only libxc_probe.o | grep -i xc_f03_version || true

echo
echo "=== linking and running against installed Libxc ==="
ifx libxc_probe.o -L"${libxc_lib}" \
    -Wl,-rpath,"${libxc_lib}" -lxcf03 -lxc -o libxc_probe

./libxc_probe