if(NOT TARGET htslib)
  find_package(htslib QUIET NO_MODULE)
  if(htslib_FOUND AND TARGET htslib::hts)
    add_library(htslib INTERFACE IMPORTED)
    target_link_libraries(htslib INTERFACE htslib::hts)
    message(STATUS "Using system htslib via config package")
  else()
    find_package(PkgConfig REQUIRED)
    pkg_check_modules(HTSLIB REQUIRED IMPORTED_TARGET htslib)
    add_library(htslib INTERFACE IMPORTED)
    target_link_libraries(htslib INTERFACE PkgConfig::HTSLIB)
    message(STATUS "Using system htslib via pkg-config")
  endif()
endif()