#!/bin/sh

# Delete all *.dif files and ddtmp.* files. If the dacdif prefix
# is changed, change that here.

find . -name "*.dif" -print0 | xargs -0 /bin/rm 2>/dev/null
find . -name "ddtmp.*" -print0 | xargs -0 /bin/rm 2>/dev/null

/bin/rm -f TEST_FAILURES.diff

# An alphabetical list of every file that may be created by the tests.

delete_list="
4096wat/logfile
4096wat/mdout.column_fft
4096wat/mdout.pure_wat
4096wat/mdout.pure_wat_efield
4096wat/mdout.pure_wat_fswitch
4096wat/mdout.pure_wat_nmr_temp
4096wat/mdout.vrand
4096wat_oct/logfile
4096wat_oct/mdcrd.pure_wat_oct
4096wat_oct/mdout.pure_wat_oct
abfqmmm/abfqmmm_dmpoh_md/abfqmmm_dmpoh_md.frc
abfqmmm/abfqmmm_dmpoh_md/abfqmmm_dmpoh_md.idrst
abfqmmm/abfqmmm_dmpoh_md/abfqmmm_dmpoh_md.out
abfqmmm/abfqmmm_dmpoh_md/abfqmmm_dmpoh_md.pdb
abfqmmm/abfqmmm_dmpoh_md/abfqmmm_dmpoh_md.rst
abfqmmm/abfqmmm_water_md/abfqmmm_water_md.frc
abfqmmm/abfqmmm_water_md/abfqmmm_water_md.idrst
abfqmmm/abfqmmm_water_md/abfqmmm_water_md.out
abfqmmm/abfqmmm_water_md/abfqmmm_water_md.pdb
abfqmmm/abfqmmm_water_sp/abfqmmm_water_sp.frc
abfqmmm/abfqmmm_water_sp/abfqmmm_water_sp.idrst
abfqmmm/abfqmmm_water_sp/abfqmmm_water_sp.out
abfqmmm/abfqmmm_water_sp/abfqmmm_water_sp.pdb
abfqmmm/adqmmm_water_md/adqmmm_water_md.frc
abfqmmm/adqmmm_water_md/adqmmm_water_md.idrst
abfqmmm/adqmmm_water_md/adqmmm_water_md.out
abfqmmm/adqmmm_water_md/adqmmm_water_md.pdb
abfqmmm/hotspot_water_md/hotspot_water_md.frc
abfqmmm/hotspot_water_md/hotspot_water_md.idrst
abfqmmm/hotspot_water_md/hotspot_water_md.out
abfqmmm/hotspot_water_md/hotspot_water_md.pdb
adenine/mdout.adenine
alpb_trx/logfile
alpb_trx/mdout.trxox
alpb_trx/mdout.trxox.nogbsa
alp/logfile
alp/mdout.alp
amoeba_formbox/amoeba_formbox.mdout
amoeba_gb1/mdout.amoeba_gb1
amoeba_jac/amoeba_jac.mdout
amoeba_wat1/amoeba_wat1.out
amoeba_wat2/amoeba_wat2.out
amoeba_wat2/ntpverlet
bintraj/bintraj.out
bintraj/mdin
bintraj/mdinfo
bintraj/mdtrj.nc
bintraj/nc_headers
bintraj/restrt
campTI/camp.p0
campTI/camp.p1
chamber/md_engine/dhfr_cmap/logfile
chamber/md_engine/dhfr_cmap/mdout.dhfr_charmm
chamber/md_engine/dhfr_cmap_pbc/logfile
chamber/md_engine/dhfr_cmap_pbc/mdout.dhfr_charmm.md
chamber/md_engine/dhfr_cmap_pbc/mdout.dhfr_charmm.min
chamber/md_engine/dhfr_cmap_pbc/mdout.dhfr_charmm_noshake.md
chamber/md_engine/dhfr_cmap_pbc/mdout.dhfr_charmm_noshake.min
chamber/md_engine/dhfr/logfile
chamber/md_engine/dhfr/mdout.dhfr_charmm
chamber/md_engine/dhfr/mdout.dhfr_charmm.min
circ_dna/logfile
circ_dna/mdout.circdna
cnstph/explicit/cpout
cnstph/explicit/mdout
cnstph/implicit/cpout
cnstph/implicit/mdout
cnste/explicit/ceout
cnste/explicit/mdout
cnste/implicit/ceout
cnste/implicit/mdout
cnstphe/explicit/cpout
cnstphe/explicit/ceout
cnstphe/explicit/mdout
cnstphe/implicit/cpout
cnstphe/implicit/ceout
cnstphe/implicit/mdout
cnstphe_merged/explicit/cpeout
cnstphe_merged/explicit/mdout
cnstphe_merged/implicit/cpeout
cnstphe_merged/implicit/mdout
cnstph_remd/Explicit_pHREM/1AKI.solv10.md1.mdout.0
cnstph_remd/Explicit_pHREM/cpout.001
cnstph_remd/Explicit_pHREM/rem.log
cnstph_remd/pHREM/cpout.pH2.5
cnstph_remd/pHREM/mdout.pH2
cnstph_remd/pHREM/rem.log
cnstph_remd/TempRem/ph4.cpout.000
cnstph_remd/TempRem/ph4.out.000
cnstph_remd/TempRem/rem.log
cnste_remd/Explicit_EREM/ceout.001
cnste_remd/Explicit_EREM/mdout.0
cnste_remd/Explicit_EREM/rem.log
cnste_remd/EREM/ceout.E0.84
cnste_remd/EREM/mdout.E0.81
cnste_remd/EREM/rem.log
cnste_remd/TempRem/E0.84.ceout.000
cnste_remd/TempRem/E0.84.out.000
cnste_remd/TempRem/rem.log
phtremd/implicit/ceout.000
phtremd/implicit/cpout.000
phtremd/implicit/mdout.rep.001
phtremd/implicit/rem.log.1
phtremd/implicit/rem.log.2
phtremd/explicit/ceout.000
phtremd/explicit/cpout.000
phtremd/explicit/mdout.rep.001
phtremd/explicit/rem.log.1
phtremd/explicit/rem.log.2
ephtremd/implicit/ceout.000
ephtremd/implicit/cpout.000
ephtremd/implicit/mdout.rep.001
ephtremd/implicit/rem.log.1
ephtremd/implicit/rem.log.2
ephtremd/implicit/rem.log.3
ephtremd/explicit/ceout.000
ephtremd/explicit/cpout.000
ephtremd/explicit/mdout.rep.001
ephtremd/explicit/rem.log.1
ephtremd/explicit/rem.log.2
ephtremd/explicit/rem.log.3
crg_reloc/1-4elec/*.out
crg_reloc/cyt/*.out
crg_reloc/misc/*.out
crg_reloc/water/*.out
cytosine/cytosine.out
cytosine/logfile
dhfr/logfile
dhfr/mdout.dhfr
dhfr/mdout.dhfr.lmodxmin
dhfr/mdout.dhfr.min
dhfr/mdout.dhfr.min_prcg
dhfr/mdout.dhfr.noboxinfo
dhfr/mdout.dhfr.noshake
dmp/mdout.dmp
dna_pol/mdout.dna_pol
emap2/emap2.x
emil/emil_multisander_gbsa/logfile.000
emil/emil_multisander_gbsa/logfile.001
emil/emil_pmemd_gbsa/emilParameters.in
emil/emil_pmemd_gbsa/emil.stderr.0.0
emil/emil_pmemd_gbsa/emil.stderr.0.1
emil/emil_pmemd_gbsa/emil.stderr.0.9
emil/emil_pmemd_gbsa/emil.stdout.dummy
emil/emil_pmemd_gbsa/logfile
emil/emil_pmemd_gbsa/mdcrd
emil/emil_pmemd_gbsa/mdin
emil/emil_pmemd_gbsa/restrt
emil/emil_pmemd_gbsa/test_timings.dat
emil/emil_pmemd_gbsa/wells.dat
emil/emil_pmemd_tip3p/emilParameters.in
emil/emil_pmemd_tip3p/emil.stderr.0.1
emil/emil_pmemd_tip3p/emil.stderr.0.5
emil/emil_pmemd_tip3p/emil.stderr.0.9
emil/emil_pmemd_tip3p/logfile
emil/emil_pmemd_tip3p/mdcrd
emil/emil_pmemd_tip3p/restrt
emil/emil_pmemd_tip3p/test_timings.dat
emil/emil_pmemd_tip3p/wells.dat
emil/emil_sander_gbsa/emilParameters.in
emil/emil_sander_gbsa/emil.stderr.0.0
emil/emil_sander_gbsa/emil.stderr.0.1
emil/emil_sander_gbsa/emil.stderr.0.9
emil/emil_sander_gbsa/mdcrd
emil/emil_sander_gbsa/restrt
emil/emil_sander_gbsa/test_timings.dat
emil/emil_sander_gbsa/wells.dat
evb/malon_bond_umb_dg_UFF_3DG/evbout
evb/malon_bond_umb_dg_UFF_3DG/malonaldehydeP_35.fchk
evb/malon_bond_umb_dg_UFF_3DG/malonaldehydeR_35.fchk
evb/malon_bond_umb_dg_UFF_3DG/malonaldehydeTS_35.fchk
evb/malon_bond_umb_dg_UFF_3DG/mdcrd
evb/malon_bond_umb_dg_UFF_3DG/mdinfo
evb/malon_bond_umb_dg_UFF_3DG/mp.out
evb/malon_bond_umb_dg_UFF_3DG/mp.rst
evb/malon_bond_umb_dg_UFF_3DG/mr.out
evb/malon_bond_umb_dg_UFF_3DG/mr.rst
evb/malon_bond_umb_dg_UFF_3DG_nmpimd_full/evbout
evb/malon_bond_umb_dg_UFF_3DG_nmpimd_full/fort.1001
evb/malon_bond_umb_dg_UFF_3DG_nmpimd_full/fort.277
evb/malon_bond_umb_dg_UFF_3DG_nmpimd_full/malonaldehydeP_35.fchk
evb/malon_bond_umb_dg_UFF_3DG_nmpimd_full/malonaldehydeR_35.fchk
evb/malon_bond_umb_dg_UFF_3DG_nmpimd_full/malonaldehydeTS_35.fchk
evb/malon_bond_umb_dg_UFF_3DG_nmpimd_full/mdcrd
evb/malon_bond_umb_dg_UFF_3DG_nmpimd_full/mdinfo
evb/malon_bond_umb_dg_UFF_3DG_nmpimd_full/mp_les.out
evb/malon_bond_umb_dg_UFF_3DG_nmpimd_full/mp_les.rst
evb/malon_bond_umb_dg_UFF_3DG_nmpimd_full/mr_les.out
evb/malon_bond_umb_dg_UFF_3DG_nmpimd_full/mr_les.rst
evb/malon_bond_umb_dg_UFF_3DG_nmpimd_full/NHC.dat
evb/malon_bond_umb_dg_UFF_3DG_nmpimd_full/numprocs.awk
evb/malon_bond_umb_dg_UFF_3DG/numprocs.awk
evb/malon_bond_umb_dg_UFF_3DG_pimd_ld_full/evbout
evb/malon_bond_umb_dg_UFF_3DG_pimd_ld_full/fort.277
evb/malon_bond_umb_dg_UFF_3DG_pimd_ld_full/malonaldehydeP_35.fchk
evb/malon_bond_umb_dg_UFF_3DG_pimd_ld_full/malonaldehydeR_35.fchk
evb/malon_bond_umb_dg_UFF_3DG_pimd_ld_full/malonaldehydeTS_35.fchk
evb/malon_bond_umb_dg_UFF_3DG_pimd_ld_full/mdcrd
evb/malon_bond_umb_dg_UFF_3DG_pimd_ld_full/mdinfo
evb/malon_bond_umb_dg_UFF_3DG_pimd_ld_full/mp_les.out
evb/malon_bond_umb_dg_UFF_3DG_pimd_ld_full/mp_les.rst
evb/malon_bond_umb_dg_UFF_3DG_pimd_ld_full/mr_les.out
evb/malon_bond_umb_dg_UFF_3DG_pimd_ld_full/mr_les.rst
evb/malon_bond_umb_dg_UFF_3DG_pimd_ld_full/numprocs.awk
evb/malon_bond_umb_dg_UFF_3DG_pimd_nhc_full/evbout
evb/malon_bond_umb_dg_UFF_3DG_pimd_nhc_full/fort.1001
evb/malon_bond_umb_dg_UFF_3DG_pimd_nhc_full/fort.277
evb/malon_bond_umb_dg_UFF_3DG_pimd_nhc_full/malonaldehydeP_35.fchk
evb/malon_bond_umb_dg_UFF_3DG_pimd_nhc_full/malonaldehydeR_35.fchk
evb/malon_bond_umb_dg_UFF_3DG_pimd_nhc_full/malonaldehydeTS_35.fchk
evb/malon_bond_umb_dg_UFF_3DG_pimd_nhc_full/mdcrd
evb/malon_bond_umb_dg_UFF_3DG_pimd_nhc_full/mdinfo
evb/malon_bond_umb_dg_UFF_3DG_pimd_nhc_full/mp_les.out
evb/malon_bond_umb_dg_UFF_3DG_pimd_nhc_full/mp_les.rst
evb/malon_bond_umb_dg_UFF_3DG_pimd_nhc_full/mr_les.out
evb/malon_bond_umb_dg_UFF_3DG_pimd_nhc_full/mr_les.rst
evb/malon_bond_umb_dg_UFF_3DG_pimd_nhc_full/NHC.dat
evb/malon_bond_umb_dg_UFF_3DG_pimd_nhc_full/numprocs.awk
evb/malon_bond_umb_dg_UFF_3DG_pimd_nhc_full_TI-MASS/evbout-.4
evb/malon_bond_umb_dg_UFF_3DG_pimd_nhc_full_TI-MASS/evbout-.8
evb/malon_bond_umb_dg_UFF_3DG_pimd_nhc_full_TI-MASS/fort.1001
evb/malon_bond_umb_dg_UFF_3DG_pimd_nhc_full_TI-MASS/fort.277
evb/malon_bond_umb_dg_UFF_3DG_pimd_nhc_full_TI-MASS/malonaldehydeP_35.fchk
evb/malon_bond_umb_dg_UFF_3DG_pimd_nhc_full_TI-MASS/malonaldehydeR_35.fchk
evb/malon_bond_umb_dg_UFF_3DG_pimd_nhc_full_TI-MASS/malonaldehydeTS_35.fchk
evb/malon_bond_umb_dg_UFF_3DG_pimd_nhc_full_TI-MASS/mdcrd
evb/malon_bond_umb_dg_UFF_3DG_pimd_nhc_full_TI-MASS/mp_les-.4.out
evb/malon_bond_umb_dg_UFF_3DG_pimd_nhc_full_TI-MASS/mp_les-.8.out
evb/malon_bond_umb_dg_UFF_3DG_pimd_nhc_full_TI-MASS/mr_les-.4.out
evb/malon_bond_umb_dg_UFF_3DG_pimd_nhc_full_TI-MASS/mr_les-.8.out
evb/malon_bond_umb_dg_UFF_3DG_pimd_nhc_full_TI-MASS/NHC.dat
evb/malon_bond_umb_dg_UFF_3DG_pimd_nhc_full_TI-MASS/numprocs.awk
evb/malon_bond_umb_GAFF/evbout
evb/malon_bond_umb_GAFF/mdcrd
evb/malon_bond_umb_GAFF_MORSIFY/evbout
evb/malon_bond_umb_GAFF_MORSIFY/mdcrd
evb/malon_bond_umb_GAFF_MORSIFY/mp.out
evb/malon_bond_umb_GAFF_MORSIFY/mr.out
evb/malon_bond_umb_GAFF_MORSIFY/numprocs.awk
evb/malon_bond_umb_GAFF_MORSIFY_XVDW/evbout
evb/malon_bond_umb_GAFF_MORSIFY_XVDW/mdcrd
evb/malon_bond_umb_GAFF_MORSIFY_XVDW/mp.out
evb/malon_bond_umb_GAFF_MORSIFY_XVDW/mr.out
evb/malon_bond_umb_GAFF_MORSIFY_XVDW/numprocs.awk
evb/malon_bond_umb_GAFF/mp.out
evb/malon_bond_umb_GAFF/mr.out
evb/malon_bond_umb_GAFF/numprocs.awk
evb/malon_dbonds_umb_dg_UFF_3DG_qi_full_2D-PMF/evbout
evb/malon_dbonds_umb_dg_UFF_3DG_qi_full_2D-PMF/fort.1001
evb/malon_dbonds_umb_dg_UFF_3DG_qi_full_2D-PMF/fort.277
evb/malon_dbonds_umb_dg_UFF_3DG_qi_full_2D-PMF/malonaldehydeP_35.fchk
evb/malon_dbonds_umb_dg_UFF_3DG_qi_full_2D-PMF/malonaldehydeR_35.fchk
evb/malon_dbonds_umb_dg_UFF_3DG_qi_full_2D-PMF/malonaldehydeTS_35.fchk
evb/malon_dbonds_umb_dg_UFF_3DG_qi_full_2D-PMF/mdcrd
evb/malon_dbonds_umb_dg_UFF_3DG_qi_full_2D-PMF/mp_les.out
evb/malon_dbonds_umb_dg_UFF_3DG_qi_full_2D-PMF/mr_les.out
evb/malon_dbonds_umb_dg_UFF_3DG_qi_full_2D-PMF/NHC.dat
evb/malon_dbonds_umb_dg_UFF_3DG_qi_full_2D-PMF/numprocs.awk
evb/malon_dbonds_umb_dg_UFF_3DG_qi_full_corrF/evbout
evb/malon_dbonds_umb_dg_UFF_3DG_qi_full_corrF/fort.1001
evb/malon_dbonds_umb_dg_UFF_3DG_qi_full_corrF/fort.277
evb/malon_dbonds_umb_dg_UFF_3DG_qi_full_corrF/malonaldehydeP_35.fchk
evb/malon_dbonds_umb_dg_UFF_3DG_qi_full_corrF/malonaldehydeR_35.fchk
evb/malon_dbonds_umb_dg_UFF_3DG_qi_full_corrF/malonaldehydeTS_35.fchk
evb/malon_dbonds_umb_dg_UFF_3DG_qi_full_corrF/mdcrd
evb/malon_dbonds_umb_dg_UFF_3DG_qi_full_corrF/mp_les.out
evb/malon_dbonds_umb_dg_UFF_3DG_qi_full_corrF/mr_les.out
evb/malon_dbonds_umb_dg_UFF_3DG_qi_full_corrF/NHC.dat
evb/malon_dbonds_umb_dg_UFF_3DG_qi_full_corrF/numprocs.awk
evb/malon_dbonds_umb_GAFF/evbout
evb/malon_dbonds_umb_GAFF/mdcrd
evb/malon_dbonds_umb_GAFF_MORSIFY/evbout
evb/malon_dbonds_umb_GAFF_MORSIFY/mdcrd
evb/malon_dbonds_umb_GAFF_MORSIFY/mp.out
evb/malon_dbonds_umb_GAFF_MORSIFY/mr.out
evb/malon_dbonds_umb_GAFF_MORSIFY_nmpimd_full/evbout
evb/malon_dbonds_umb_GAFF_MORSIFY_nmpimd_full/fort.1001
evb/malon_dbonds_umb_GAFF_MORSIFY_nmpimd_full/fort.277
evb/malon_dbonds_umb_GAFF_MORSIFY_nmpimd_full/mdcrd
evb/malon_dbonds_umb_GAFF_MORSIFY_nmpimd_full/mp_les.out
evb/malon_dbonds_umb_GAFF_MORSIFY_nmpimd_full/mp_les.rst
evb/malon_dbonds_umb_GAFF_MORSIFY_nmpimd_full/mr_les.out
evb/malon_dbonds_umb_GAFF_MORSIFY_nmpimd_full/mr_les.rst
evb/malon_dbonds_umb_GAFF_MORSIFY_nmpimd_full/NHC.dat
evb/malon_dbonds_umb_GAFF_MORSIFY_nmpimd_full/numprocs.awk
evb/malon_dbonds_umb_GAFF_MORSIFY/numprocs.awk
evb/malon_dbonds_umb_GAFF_MORSIFY_pimd_ld_full/evbout
evb/malon_dbonds_umb_GAFF_MORSIFY_pimd_ld_full/fort.277
evb/malon_dbonds_umb_GAFF_MORSIFY_pimd_ld_full/mdcrd
evb/malon_dbonds_umb_GAFF_MORSIFY_pimd_ld_full/mp_les.out
evb/malon_dbonds_umb_GAFF_MORSIFY_pimd_ld_full/mp_les.rst
evb/malon_dbonds_umb_GAFF_MORSIFY_pimd_ld_full/mr_les.out
evb/malon_dbonds_umb_GAFF_MORSIFY_pimd_ld_full/mr_les.rst
evb/malon_dbonds_umb_GAFF_MORSIFY_pimd_ld_full/numprocs.awk
evb/malon_dbonds_umb_GAFF_MORSIFY_pimd_nhc_full/evbout
evb/malon_dbonds_umb_GAFF_MORSIFY_pimd_nhc_full/fort.1001
evb/malon_dbonds_umb_GAFF_MORSIFY_pimd_nhc_full/fort.277
evb/malon_dbonds_umb_GAFF_MORSIFY_pimd_nhc_full/mdcrd
evb/malon_dbonds_umb_GAFF_MORSIFY_pimd_nhc_full/mp_les.out
evb/malon_dbonds_umb_GAFF_MORSIFY_pimd_nhc_full/mp_les.rst
evb/malon_dbonds_umb_GAFF_MORSIFY_pimd_nhc_full/mr_les.out
evb/malon_dbonds_umb_GAFF_MORSIFY_pimd_nhc_full/mr_les.rst
evb/malon_dbonds_umb_GAFF_MORSIFY_pimd_nhc_full/NHC.dat
evb/malon_dbonds_umb_GAFF_MORSIFY_pimd_nhc_full/numprocs.awk
evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW/evbout
evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_EXP-XCH/evbout
evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_EXP-XCH/mdcrd
evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_EXP-XCH/mp.out
evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_EXP-XCH/mr.out
evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_EXP-XCH_nmpimd_full/evbout
evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_EXP-XCH_nmpimd_full/fort.1001
evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_EXP-XCH_nmpimd_full/fort.277
evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_EXP-XCH_nmpimd_full/mdcrd
evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_EXP-XCH_nmpimd_full/mp_les.out
evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_EXP-XCH_nmpimd_full/mp_les.rst
evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_EXP-XCH_nmpimd_full/mr_les.out
evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_EXP-XCH_nmpimd_full/mr_les.rst
evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_EXP-XCH_nmpimd_full/NHC.dat
evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_EXP-XCH_nmpimd_full/numprocs.awk
evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_EXP-XCH/numprocs.awk
evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_EXP-XCH_pimd_ld_full/evbout
evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_EXP-XCH_pimd_ld_full/fort.277
evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_EXP-XCH_pimd_ld_full/mdcrd
evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_EXP-XCH_pimd_ld_full/mp_les.out
evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_EXP-XCH_pimd_ld_full/mp_les.rst
evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_EXP-XCH_pimd_ld_full/mr_les.out
evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_EXP-XCH_pimd_ld_full/mr_les.rst
evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_EXP-XCH_pimd_ld_full/numprocs.awk
evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_EXP-XCH_pimd_nhc_full/evbout
evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_EXP-XCH_pimd_nhc_full/fort.1001
evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_EXP-XCH_pimd_nhc_full/fort.277
evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_EXP-XCH_pimd_nhc_full/mdcrd
evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_EXP-XCH_pimd_nhc_full/mp_les.out
evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_EXP-XCH_pimd_nhc_full/mp_les.rst
evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_EXP-XCH_pimd_nhc_full/mr_les.out
evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_EXP-XCH_pimd_nhc_full/mr_les.rst
evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_EXP-XCH_pimd_nhc_full/NHC.dat
evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_EXP-XCH_pimd_nhc_full/numprocs.awk
evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_GAUSS-XCH/evbout
evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_GAUSS-XCH/mdcrd
evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_GAUSS-XCH/mp.out
evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_GAUSS-XCH/mr.out
evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_GAUSS-XCH_nmpimd_full/evbout
evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_GAUSS-XCH_nmpimd_full/fort.1001
evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_GAUSS-XCH_nmpimd_full/fort.277
evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_GAUSS-XCH_nmpimd_full/mdcrd
evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_GAUSS-XCH_nmpimd_full/mp_les.out
evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_GAUSS-XCH_nmpimd_full/mp_les.rst
evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_GAUSS-XCH_nmpimd_full/mr_les.out
evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_GAUSS-XCH_nmpimd_full/mr_les.rst
evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_GAUSS-XCH_nmpimd_full/NHC.dat
evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_GAUSS-XCH_nmpimd_full/numprocs.awk
evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_GAUSS-XCH/numprocs.awk
evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_GAUSS-XCH_pimd_ld_full/evbout
evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_GAUSS-XCH_pimd_ld_full/fort.277
evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_GAUSS-XCH_pimd_ld_full/mdcrd
evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_GAUSS-XCH_pimd_ld_full/mp_les.out
evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_GAUSS-XCH_pimd_ld_full/mp_les.rst
evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_GAUSS-XCH_pimd_ld_full/mr_les.out
evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_GAUSS-XCH_pimd_ld_full/mr_les.rst
evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_GAUSS-XCH_pimd_ld_full/numprocs.awk
evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_GAUSS-XCH_pimd_nhc_full/evbout
evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_GAUSS-XCH_pimd_nhc_full/fort.1001
evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_GAUSS-XCH_pimd_nhc_full/fort.277
evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_GAUSS-XCH_pimd_nhc_full/mdcrd
evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_GAUSS-XCH_pimd_nhc_full/mp_les.out
evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_GAUSS-XCH_pimd_nhc_full/mp_les.rst
evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_GAUSS-XCH_pimd_nhc_full/mr_les.out
evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_GAUSS-XCH_pimd_nhc_full/mr_les.rst
evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_GAUSS-XCH_pimd_nhc_full/NHC.dat
evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_GAUSS-XCH_pimd_nhc_full/numprocs.awk
evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW/mdcrd
evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW/mp.out
evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW/mr.out
evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW/numprocs.awk
evb/malon_dbonds_umb_GAFF/mp.out
evb/malon_dbonds_umb_GAFF/mr.out
evb/malon_dbonds_umb_GAFF/numprocs.awk
evb/malon_dbond_umb_dg_UFF_3DG_pimd_nhc_full_TI-MASS/evbout
evb/malon_dbond_umb_dg_UFF_3DG_pimd_nhc_full_TI-MASS/evbout-.4
evb/malon_dbond_umb_dg_UFF_3DG_pimd_nhc_full_TI-MASS/evbout-.8
evb/malon_dbond_umb_dg_UFF_3DG_pimd_nhc_full_TI-MASS/fort.1001
evb/malon_dbond_umb_dg_UFF_3DG_pimd_nhc_full_TI-MASS/fort.277
evb/malon_dbond_umb_dg_UFF_3DG_pimd_nhc_full_TI-MASS/malonaldehydeP_35.fchk
evb/malon_dbond_umb_dg_UFF_3DG_pimd_nhc_full_TI-MASS/malonaldehydeR_35.fchk
evb/malon_dbond_umb_dg_UFF_3DG_pimd_nhc_full_TI-MASS/malonaldehydeTS_35.fchk
evb/malon_dbond_umb_dg_UFF_3DG_pimd_nhc_full_TI-MASS/mdcrd
evb/malon_dbond_umb_dg_UFF_3DG_pimd_nhc_full_TI-MASS/mp_les-.4.out
evb/malon_dbond_umb_dg_UFF_3DG_pimd_nhc_full_TI-MASS/mp_les-.8.out
evb/malon_dbond_umb_dg_UFF_3DG_pimd_nhc_full_TI-MASS/mr_les-.4.out
evb/malon_dbond_umb_dg_UFF_3DG_pimd_nhc_full_TI-MASS/mr_les-.8.out
evb/malon_dbond_umb_dg_UFF_3DG_pimd_nhc_full_TI-MASS/NHC.dat
evb/malon_dbond_umb_dg_UFF_3DG_pimd_nhc_full_TI-MASS/numprocs.awk
evb/malon_emap_GAFF_MORSIFY/evbout
evb/malon_emap_GAFF_MORSIFY/mdcrd
evb/malon_emap_GAFF_MORSIFY/mp.out
evb/malon_emap_GAFF_MORSIFY/mr.out
evb/malon_emap_GAFF_MORSIFY/numprocs.awk
evb/malon_emap_GAFF_MORSIFY_XVDW/evbout
evb/malon_emap_GAFF_MORSIFY_XVDW/mdcrd
evb/malon_emap_GAFF_MORSIFY_XVDW/mp.out
evb/malon_emap_GAFF_MORSIFY_XVDW/mr.out
evb/malon_emap_GAFF_MORSIFY_XVDW/numprocs.awk
evb/poh_dbonds_umb_dg_UFF_3DG/2hydroxypyridine_56.fchk
evb/poh_dbonds_umb_dg_UFF_3DG/2hydroxypyridine_TS_56_vtight.fchk
evb/poh_dbonds_umb_dg_UFF_3DG/evbout
evb/poh_dbonds_umb_dg_UFF_3DG/mdcrd
evb/poh_dbonds_umb_dg_UFF_3DG/mdinfo
evb/poh_dbonds_umb_dg_UFF_3DG/numprocs.awk
evb/poh_dbonds_umb_dg_UFF_3DG/poh.out
evb/poh_dbonds_umb_dg_UFF_3DG/poh.rst
evb/poh_dbonds_umb_dg_UFF_3DG/po.out
evb/poh_dbonds_umb_dg_UFF_3DG/po.rst
evb/poh_dbonds_umb_dg_UFF_3DG/pyridone_56.fchk
evb/poh_dbonds_umb_dg_UFF_9DG/2hydroxypyridine_56.fchk
evb/poh_dbonds_umb_dg_UFF_9DG/2hydroxypyridine_TS_56_vtight.fchk
evb/poh_dbonds_umb_dg_UFF_9DG/irc_minusonefourth_56.fchk
evb/poh_dbonds_umb_dg_UFF_9DG/irc_minusonehalf_56.fchk
evb/poh_dbonds_umb_dg_UFF_9DG/irc_plusonefourth_56.fchk
evb/poh_dbonds_umb_dg_UFF_9DG/irc_plusonehalf_56.fchk
evb/poh_dbonds_umb_dg_UFF_9DG_nmpimd_full/2hydroxypyridine_56.fchk
evb/poh_dbonds_umb_dg_UFF_9DG_nmpimd_full/2hydroxypyridine_TS_56_vtight.fchk
evb/poh_dbonds_umb_dg_UFF_9DG_nmpimd_full/irc_minusonefourth_56.fchk
evb/poh_dbonds_umb_dg_UFF_9DG_nmpimd_full/irc_minusonehalf_56.fchk
evb/poh_dbonds_umb_dg_UFF_9DG_nmpimd_full/irc_plusonefourth_56.fchk
evb/poh_dbonds_umb_dg_UFF_9DG_nmpimd_full/irc_plusonehalf_56.fchk
evb/poh_dbonds_umb_dg_UFF_9DG_nmpimd_full/numprocs.awk
evb/poh_dbonds_umb_dg_UFF_9DG_nmpimd_full/onehalfP_56.fchk
evb/poh_dbonds_umb_dg_UFF_9DG_nmpimd_full/onehalfR_56.fchk
evb/poh_dbonds_umb_dg_UFF_9DG_nmpimd_full/pyridone_56.fchk
evb/poh_dbonds_umb_dg_UFF_9DG_nmpimd_full_TST-freqf/2hydroxypyridine_56.fchk
evb/poh_dbonds_umb_dg_UFF_9DG_nmpimd_full_TST-freqf/2hydroxypyridine_TS_56_vtight.fchk
evb/poh_dbonds_umb_dg_UFF_9DG_nmpimd_full_TST-freqf/irc_minusonefourth_56.fchk
evb/poh_dbonds_umb_dg_UFF_9DG_nmpimd_full_TST-freqf/irc_minusonehalf_56.fchk
evb/poh_dbonds_umb_dg_UFF_9DG_nmpimd_full_TST-freqf/irc_plusonefourth_56.fchk
evb/poh_dbonds_umb_dg_UFF_9DG_nmpimd_full_TST-freqf/irc_plusonehalf_56.fchk
evb/poh_dbonds_umb_dg_UFF_9DG_nmpimd_full_TST-freqf/numprocs.awk
evb/poh_dbonds_umb_dg_UFF_9DG_nmpimd_full_TST-freqf/onehalfP_56.fchk
evb/poh_dbonds_umb_dg_UFF_9DG_nmpimd_full_TST-freqf/onehalfR_56.fchk
evb/poh_dbonds_umb_dg_UFF_9DG_nmpimd_full_TST-freqf/pyridone_56.fchk
evb/poh_dbonds_umb_dg_UFF_9DG/numprocs.awk
evb/poh_dbonds_umb_dg_UFF_9DG/onehalfP_56.fchk
evb/poh_dbonds_umb_dg_UFF_9DG/onehalfR_56.fchk
evb/poh_dbonds_umb_dg_UFF_9DG_pimd_ld_full/2hydroxypyridine_56.fchk
evb/poh_dbonds_umb_dg_UFF_9DG_pimd_ld_full/2hydroxypyridine_TS_56_vtight.fchk
evb/poh_dbonds_umb_dg_UFF_9DG_pimd_ld_full/irc_minusonefourth_56.fchk
evb/poh_dbonds_umb_dg_UFF_9DG_pimd_ld_full/irc_minusonehalf_56.fchk
evb/poh_dbonds_umb_dg_UFF_9DG_pimd_ld_full/irc_plusonefourth_56.fchk
evb/poh_dbonds_umb_dg_UFF_9DG_pimd_ld_full/irc_plusonehalf_56.fchk
evb/poh_dbonds_umb_dg_UFF_9DG_pimd_ld_full/numprocs.awk
evb/poh_dbonds_umb_dg_UFF_9DG_pimd_ld_full/onehalfP_56.fchk
evb/poh_dbonds_umb_dg_UFF_9DG_pimd_ld_full/onehalfR_56.fchk
evb/poh_dbonds_umb_dg_UFF_9DG_pimd_ld_full/pyridone_56.fchk
evb/poh_dbonds_umb_dg_UFF_9DG_pimd_nhc_full/2hydroxypyridine_56.fchk
evb/poh_dbonds_umb_dg_UFF_9DG_pimd_nhc_full/2hydroxypyridine_TS_56_vtight.fchk
evb/poh_dbonds_umb_dg_UFF_9DG_pimd_nhc_full/irc_minusonefourth_56.fchk
evb/poh_dbonds_umb_dg_UFF_9DG_pimd_nhc_full/irc_minusonehalf_56.fchk
evb/poh_dbonds_umb_dg_UFF_9DG_pimd_nhc_full/irc_plusonefourth_56.fchk
evb/poh_dbonds_umb_dg_UFF_9DG_pimd_nhc_full/irc_plusonehalf_56.fchk
evb/poh_dbonds_umb_dg_UFF_9DG_pimd_nhc_full/numprocs.awk
evb/poh_dbonds_umb_dg_UFF_9DG_pimd_nhc_full/onehalfP_56.fchk
evb/poh_dbonds_umb_dg_UFF_9DG_pimd_nhc_full/onehalfR_56.fchk
evb/poh_dbonds_umb_dg_UFF_9DG_pimd_nhc_full/pyridone_56.fchk
evb/poh_dbonds_umb_dg_UFF_9DG/pyridone_56.fchk
gact_ips/logfile
gact_ips/mdout.ips
gact_ips/mdout.ips_dfft
gact_ips/mdout.ipsnve
gact_ips/mdout.ips_sgld
gact_ips/mdout.ips_vacuum
gb1_cox2/cox2.out
gb1_cox2/logfile
gb2_trx/logfile
gb2_trx/mdout.trxox
gb2_trx/mdout.trxox.nogbsa
gb7_trx/logfile
gb7_trx/mdout.trxox
gb7_trx/mdout.trxox_md
gb8_trx/logfile
gb8_trx/mdout.trxox
gb8_trx/mdout.trxox_md
gbneck2nu_test/logfile
gbneck2nu_test/mdout.1hji_md
gb_rna/logfile
gb_rna/mdout.gbrna
gb_rna/mdout.gbrna.ips
gb_rna/mdout.gbrna.ln
gb_rna/mdout.gbrna.min
gb_rna/mdout.gbrna.sgld
gbsa_xfin/logfile
gbsa_xfin/mdout.gbsa
h_rem/rem.pmemd.MPI.log
h_rem/rem.sander.MPI.log
iapbs_radi/*.out iapbs_radi/mdin*
idecomp1/decomp.out
idecomp4/decomp.out
iwrap2/dummy
iwrap2/mdin
iwrap2/mdinfo
jar/dist_vs_t
jar/mdout.jar
jar_multi/dist_vs_t.000
jar_multi/dist_vs_t.001
jar_multi/mdout.jar.000
jar_multi/mdout.jar.001
LES_CUT/md.LES.out
LES_GB/les.gb1.diffcrd.out
LES_GB/les.gb1.samecrd.out
LES_GB/les.gb5.samecrd.out
LES_GB/les.gb7.rdt.out
LES_GB/les.gb7.samecrd.out
LES/LES.crd
LES/LES.prmtop
LES/mdcrd
LES/md.LES.out
LES_noPME/md.out
LES_noPME/md.rdiel.out
LES/output_
LES_TEMP/2temp.out
mcwat/mdout.mcwat
mmpbsa_py/01_Generalized_Born/FINAL_RESULTS_MMPBSA.dat
mmpbsa_py/02_Poisson_Boltzmann/FINAL_RESULTS_MMPBSA.dat
mmpbsa_py/03_Alanine_Scanning/FINAL_RESULTS_MMPBSA.dat
mmpbsa_py/04_Per_Residue_Decomp/FINAL_DECOMP_MMPBSA.dat
mmpbsa_py/04_Per_Residue_Decomp/FINAL_RESULTS_MMPBSA.dat
mmpbsa_py/05_Pairwise_Decomp/FINAL_DECOMP_MMPBSA.dat
mmpbsa_py/05_Pairwise_Decomp/FINAL_RESULTS_MMPBSA.dat
mmpbsa_py/06_NAB_Nmode/FINAL_RESULTS_MMPBSA.dat
mmpbsa_py/07_Comprehensive/FINAL_DECOMP_MMPBSA_2.dat
mmpbsa_py/07_Comprehensive/FINAL_DECOMP_MMPBSA.dat
mmpbsa_py/07_Comprehensive/FINAL_RESULTS_MMPBSA_1.dat
mmpbsa_py/07_Comprehensive/FINAL_RESULTS_MMPBSA_2.dat
mmpbsa_py/08_Stability/FINAL_DECOMP_MMPBSA1.dat
mmpbsa_py/08_Stability/FINAL_DECOMP_MMPBSA2.dat
mmpbsa_py/08_Stability/FINAL_RESULTS_MMPBSA1.dat
mmpbsa_py/08_Stability/FINAL_RESULTS_MMPBSA2.dat
mtmdtest/mtmdtest.mdcrd
mtmdtest/mtmdtest.out
nc_restart/MD_ncrestart_write/md.in
nc_restart/MD_ncrestart_write/mdinfo
nc_restart/MD_ncrestart_write/md.nc
nc_restart/MD_ncrestart_write/md.out
nc_restart/MD_ncrestart_write/ncmd.rst7
nc_restart/Min_ncrestart_write/mdinfo
nc_restart/Min_ncrestart_write/min.in
nc_restart/Min_ncrestart_write/min.nc
nc_restart/Min_ncrestart_write/min.out
nc_restart/Min_ncrestart_write/ncmin.rst7
nc_restart/refMD_ncrestart/md.in
nc_restart/refMD_ncrestart/mdinfo
nc_restart/refMD_ncrestart/md.nc
nc_restart/restartMD.ntx1/md1.rst7
nc_restart/restartMD.ntx1/md.in
nc_restart/restartMD.ntx1/mdinfo
nc_restart/restartMD.ntx1/md.nc
nc_restart/restartMD.ntx5/md1.rst7
nc_restart/restartMD.ntx5/md.in
nc_restart/restartMD.ntx5/mdinfo
nc_restart/restartMD.ntx5/md.nc
neb-testcases/neb_*/*.inf
neb-testcases/neb_*/*.mdcrd
neb-testcases/neb_*/mdin
neb-testcases/neb_*/*.out
neb-testcases/neb_*/*.rst
newton_raph/nmd_min.out
nmode/lmode.head
nmode/lvibs.out
nmode/vecs
nmode/vibs.out
nmode/vibsr.out
noesy/noesy.out
nonper/mdout.belly
nonper/mdout.belly.mask
nonper/mdout.cap
nonper/mdout.min
nonper/mdout.nocut
nonper/mdout.nonper
pcsa/stem.csa2.o
pcsa/stem.csa_min.o
pcsa/stem.csa.o
pcsa/stem.dip.o
pheMTI/out.0
pheMTI/out.1
pheMTI/out.lambda0.p0
pheMTI/out.lambda1.p0
PIMD/full_cmd_water/equilib/cmd_bead1.mdcrd
PIMD/full_cmd_water/equilib/cmd_bead1.mdinfo
PIMD/full_cmd_water/equilib/cmd_bead1.out
PIMD/full_cmd_water/equilib/cmd_bead1.rst
PIMD/full_cmd_water/equilib/cmd_bead2.mdcrd
PIMD/full_cmd_water/equilib/cmd_bead2.mdinfo
PIMD/full_cmd_water/equilib/cmd_bead2.out
PIMD/full_cmd_water/equilib/cmd_bead2.rst
PIMD/full_cmd_water/equilib/cmd_bead3.mdcrd
PIMD/full_cmd_water/equilib/cmd_bead3.mdinfo
PIMD/full_cmd_water/equilib/cmd_bead3.out
PIMD/full_cmd_water/equilib/cmd_bead3.rst
PIMD/full_cmd_water/equilib/cmd_bead4.mdcrd
PIMD/full_cmd_water/equilib/cmd_bead4.mdinfo
PIMD/full_cmd_water/equilib/cmd_bead4.out
PIMD/full_cmd_water/equilib/cmd_bead4.rst
PIMD/full_cmd_water/equilib/cmd.out
PIMD/full_cmd_water/equilib/CMD_position.dat
PIMD/full_cmd_water/equilib/cmd_sander.out
PIMD/full_cmd_water/equilib/CMD_velocity.dat
PIMD/full_cmd_water/equilib/NHC.dat
PIMD/full_cmd_water/restart/cmd_bead1.mdcrd
PIMD/full_cmd_water/restart/cmd_bead1.mdinfo
PIMD/full_cmd_water/restart/cmd_bead1.out
PIMD/full_cmd_water/restart/cmd_bead1.rst
PIMD/full_cmd_water/restart/cmd_bead2.mdcrd
PIMD/full_cmd_water/restart/cmd_bead2.mdinfo
PIMD/full_cmd_water/restart/cmd_bead2.out
PIMD/full_cmd_water/restart/cmd_bead2.rst
PIMD/full_cmd_water/restart/cmd_bead3.mdcrd
PIMD/full_cmd_water/restart/cmd_bead3.mdinfo
PIMD/full_cmd_water/restart/cmd_bead3.out
PIMD/full_cmd_water/restart/cmd_bead3.rst
PIMD/full_cmd_water/restart/cmd_bead4.mdcrd
PIMD/full_cmd_water/restart/cmd_bead4.mdinfo
PIMD/full_cmd_water/restart/cmd_bead4.out
PIMD/full_cmd_water/restart/cmd_bead4.rst
PIMD/full_cmd_water/restart/cmd.out
PIMD/full_cmd_water/restart/CMD_position.dat
PIMD/full_cmd_water/restart/cmd_sander.out
PIMD/full_cmd_water/restart/CMD_velocity.dat
PIMD/full_cmd_water/restart/NHC.dat
PIMD/full_cmd_water/start/cmd_bead1.mdcrd
PIMD/full_cmd_water/start/cmd_bead1.mdinfo
PIMD/full_cmd_water/start/cmd_bead1.out
PIMD/full_cmd_water/start/cmd_bead1.rst
PIMD/full_cmd_water/start/cmd_bead2.mdcrd
PIMD/full_cmd_water/start/cmd_bead2.mdinfo
PIMD/full_cmd_water/start/cmd_bead2.out
PIMD/full_cmd_water/start/cmd_bead2.rst
PIMD/full_cmd_water/start/cmd_bead3.mdcrd
PIMD/full_cmd_water/start/cmd_bead3.mdinfo
PIMD/full_cmd_water/start/cmd_bead3.out
PIMD/full_cmd_water/start/cmd_bead3.rst
PIMD/full_cmd_water/start/cmd_bead4.mdcrd
PIMD/full_cmd_water/start/cmd_bead4.mdinfo
PIMD/full_cmd_water/start/cmd_bead4.out
PIMD/full_cmd_water/start/cmd_bead4.rst
PIMD/full_cmd_water/start/cmd.out
PIMD/full_cmd_water/start/CMD_position.dat
PIMD/full_cmd_water/start/cmd_sander.out
PIMD/full_cmd_water/start/CMD_velocity.dat
PIMD/full_cmd_water/start/NHC.dat
PIMD/full_nmpimd_water/bead1.mdcrd
PIMD/full_nmpimd_water/bead1.mdinfo
PIMD/full_nmpimd_water/bead1.out
PIMD/full_nmpimd_water/bead1.rst
PIMD/full_nmpimd_water/bead2.mdcrd
PIMD/full_nmpimd_water/bead2.mdinfo
PIMD/full_nmpimd_water/bead2.out
PIMD/full_nmpimd_water/bead2.rst
PIMD/full_nmpimd_water/bead3.mdcrd
PIMD/full_nmpimd_water/bead3.mdinfo
PIMD/full_nmpimd_water/bead3.out
PIMD/full_nmpimd_water/bead3.rst
PIMD/full_nmpimd_water/bead4.mdcrd
PIMD/full_nmpimd_water/bead4.mdinfo
PIMD/full_nmpimd_water/bead4.out
PIMD/full_nmpimd_water/bead4.rst
PIMD/full_nmpimd_water/NHC.dat
PIMD/full_nmpimd_water/nmpimd.out
PIMD/full_nmpimd_water/sander.out
PIMD/full_pimd_amoeba/bead1.mdinfo
PIMD/full_pimd_amoeba/bead1.out
PIMD/full_pimd_amoeba/bead1.rst
PIMD/full_pimd_amoeba/bead2.mdinfo
PIMD/full_pimd_amoeba/bead2.out
PIMD/full_pimd_amoeba/bead2.rst
PIMD/full_pimd_amoeba/bead3.mdinfo
PIMD/full_pimd_amoeba/bead3.out
PIMD/full_pimd_amoeba/bead3.rst
PIMD/full_pimd_amoeba/bead4.mdinfo
PIMD/full_pimd_amoeba/bead4.out
PIMD/full_pimd_amoeba/bead4.rst
PIMD/full_pimd_amoeba/pimd_amoeba.out
PIMD/full_pimd_amoeba/sander.out
PIMD/full_pimd_ln_water/bead1.mdcrd
PIMD/full_pimd_ln_water/bead1.mdinfo
PIMD/full_pimd_ln_water/bead1.out
PIMD/full_pimd_ln_water/bead1.rst
PIMD/full_pimd_ln_water/bead2.mdcrd
PIMD/full_pimd_ln_water/bead2.mdinfo
PIMD/full_pimd_ln_water/bead2.out
PIMD/full_pimd_ln_water/bead2.rst
PIMD/full_pimd_ln_water/bead3.mdcrd
PIMD/full_pimd_ln_water/bead3.mdinfo
PIMD/full_pimd_ln_water/bead3.out
PIMD/full_pimd_ln_water/bead3.rst
PIMD/full_pimd_ln_water/bead4.mdcrd
PIMD/full_pimd_ln_water/bead4.mdinfo
PIMD/full_pimd_ln_water/bead4.out
PIMD/full_pimd_ln_water/bead4.rst
PIMD/full_pimd_ln_water/pimd_ln.out
PIMD/full_pimd_ln_water/sander.out
PIMD/full_pimd_nhc_water/bead1.mdcrd
PIMD/full_pimd_nhc_water/bead1.mdinfo
PIMD/full_pimd_nhc_water/bead1.out
PIMD/full_pimd_nhc_water/bead1.rst
PIMD/full_pimd_nhc_water/bead2.mdcrd
PIMD/full_pimd_nhc_water/bead2.mdinfo
PIMD/full_pimd_nhc_water/bead2.out
PIMD/full_pimd_nhc_water/bead2.rst
PIMD/full_pimd_nhc_water/bead3.mdcrd
PIMD/full_pimd_nhc_water/bead3.mdinfo
PIMD/full_pimd_nhc_water/bead3.out
PIMD/full_pimd_nhc_water/bead3.rst
PIMD/full_pimd_nhc_water/bead4.mdcrd
PIMD/full_pimd_nhc_water/bead4.mdinfo
PIMD/full_pimd_nhc_water/bead4.out
PIMD/full_pimd_nhc_water/bead4.rst
PIMD/full_pimd_nhc_water/NHC.dat
PIMD/full_pimd_nhc_water/pimd_nhc.out
PIMD/full_pimd_nhc_water/sander.out
PIMD/full_pimd_ntp_water/bead1.mdcrd
PIMD/full_pimd_ntp_water/bead1.mdinfo
PIMD/full_pimd_ntp_water/bead1.out
PIMD/full_pimd_ntp_water/bead1.rst
PIMD/full_pimd_ntp_water/bead2.mdcrd
PIMD/full_pimd_ntp_water/bead2.mdinfo
PIMD/full_pimd_ntp_water/bead2.out
PIMD/full_pimd_ntp_water/bead2.rst
PIMD/full_pimd_ntp_water/bead3.mdcrd
PIMD/full_pimd_ntp_water/bead3.mdinfo
PIMD/full_pimd_ntp_water/bead3.out
PIMD/full_pimd_ntp_water/bead3.rst
PIMD/full_pimd_ntp_water/bead4.mdcrd
PIMD/full_pimd_ntp_water/bead4.mdinfo
PIMD/full_pimd_ntp_water/bead4.out
PIMD/full_pimd_ntp_water/bead4.rst
PIMD/full_pimd_ntp_water/NHC.dat
PIMD/full_pimd_ntp_water/pimd_ntp.out
PIMD/full_pimd_ntp_water/sander.out
PIMD/full_rpmd_water/bead1.mdcrd
PIMD/full_rpmd_water/bead1.mdinfo
PIMD/full_rpmd_water/bead1.mdvel
PIMD/full_rpmd_water/bead1.out
PIMD/full_rpmd_water/bead1.rst
PIMD/full_rpmd_water/bead2.mdcrd
PIMD/full_rpmd_water/bead2.mdinfo
PIMD/full_rpmd_water/bead2.mdvel
PIMD/full_rpmd_water/bead2.out
PIMD/full_rpmd_water/bead2.rst
PIMD/full_rpmd_water/bead3.mdcrd
PIMD/full_rpmd_water/bead3.mdinfo
PIMD/full_rpmd_water/bead3.mdvel
PIMD/full_rpmd_water/bead3.out
PIMD/full_rpmd_water/bead3.rst
PIMD/full_rpmd_water/bead4.mdcrd
PIMD/full_rpmd_water/bead4.mdinfo
PIMD/full_rpmd_water/bead4.mdvel
PIMD/full_rpmd_water/bead4.out
PIMD/full_rpmd_water/bead4.rst
PIMD/full_rpmd_water/rpmd.out
PIMD/part_cmd_water/equilib/.out
PIMD/part_cmd_water/equilib/cmd.out
PIMD/part_cmd_water/equilib/CMD_position.dat
PIMD/part_cmd_water/equilib/CMD_velocity.dat
PIMD/part_cmd_water/equilib/fort.277
PIMD/part_cmd_water/equilib/h2o_les.crd
PIMD/part_cmd_water/equilib/h2o_les.rst
PIMD/part_cmd_water/equilib/h2o_les.top
PIMD/part_cmd_water/equilib/mdinfo
PIMD/part_cmd_water/equilib/NHC.dat
PIMD/part_cmd_water/restart/cmd.out
PIMD/part_cmd_water/restart/CMD_position.dat
PIMD/part_cmd_water/restart/CMD_velocity.dat
PIMD/part_cmd_water/restart/fort.277
PIMD/part_cmd_water/restart/h2o_les.rst
PIMD/part_cmd_water/restart/mdinfo
PIMD/part_cmd_water/restart/NHC.dat
PIMD/part_cmd_water/start/cmd.out
PIMD/part_cmd_water/start/CMD_position.dat
PIMD/part_cmd_water/start/CMD_velocity.dat
PIMD/part_cmd_water/start/fort.277
PIMD/part_cmd_water/start/h2o_les.rst
PIMD/part_cmd_water/start/mdinfo
PIMD/part_cmd_water/start/NHC.dat
PIMD/part_nmpimd_helium/fort.277
PIMD/part_nmpimd_helium/hef_pimd.out
PIMD/part_nmpimd_helium/mdcrd
PIMD/part_nmpimd_helium/mdinfo
PIMD/part_nmpimd_helium/NHC.dat
PIMD/part_nmpimd_helium/restrt
PIMD/part_nmpimd_ntp/butane_p24.mdcrd
PIMD/part_nmpimd_ntp/butane_p24.rst
PIMD/part_nmpimd_ntp/fort.277
PIMD/part_nmpimd_ntp/mdinfo
PIMD/part_nmpimd_ntp/NHC.dat
PIMD/part_nmpimd_ntp/ntp_nmpimd.out
PIMD/part_nmpimd_water/.out
PIMD/part_nmpimd_water/dummy
PIMD/part_nmpimd_water/h2o_les.crd
PIMD/part_nmpimd_water/h2o_les.top
PIMD/part_nmpimd_water/mdinfo
PIMD/part_nmpimd_water/NHC.dat
PIMD/part_nmpimd_water/nmpimd.in
PIMD/part_nmpimd_water/nmpimd.out
PIMD/part_nmpimd_water/restrt
PIMD/part_pimd_helium/fort.277
PIMD/part_pimd_helium/hef_pimd.out
PIMD/part_pimd_helium/mdcrd
PIMD/part_pimd_helium/mdinfo
PIMD/part_pimd_helium/NHC.dat
PIMD/part_pimd_helium/restrt
PIMD/part_pimd_spcfw/.out
PIMD/part_pimd_spcfw/fort.277
PIMD/part_pimd_spcfw/mdinfo
PIMD/part_pimd_spcfw/spcfw_pimd.mdcrd
PIMD/part_pimd_spcfw/spcfw_pimd.out
PIMD/part_pimd_spcfw/spcfw_pimd.rst
PIMD/part_pimd_spcfw/spcfw_pimd.top
PIMD/part_pimd_spcfw/spcfw_pimd.xyz
PIMD/part_pimd_water/.out
PIMD/part_pimd_water/dummy
PIMD/part_pimd_water/h2o_les.mdcrd
PIMD/part_pimd_water/h2o_les.rst
PIMD/part_pimd_water/mdinfo
PIMD/part_pimd_water/pimd.in
PIMD/part_pimd_water/pimd.out
PIMD/part_rpmd_water/.out
PIMD/part_rpmd_water/fort.277
PIMD/part_rpmd_water/mdcrd
PIMD/part_rpmd_water/mdinfo
PIMD/part_rpmd_water/mdvel
PIMD/part_rpmd_water/restrt
PIMD/part_rpmd_water/spcfw_rpmd.out
PIMD/part_rpmd_water/spcfw_rpmd.top
PIMD/part_rpmd_water/spcfw_rpmd.xyz
plane_plane_restraint/dinuc_pln_vs_t
plane_plane_restraint/dinuc_plpt_vs_t
plane_plane_restraint/mdout.dinucAU_pln
plane_plane_restraint/mdout.dinucAU_plpt
polarizable_water/mdout.polwat
qmmm2/1-2-ethanediol_PM3CARB1/ethanediol_md.out
qmmm2/1NLN_periodic_lnk_atoms/mdout.1NLN_MD_ntb1
qmmm2/1NLN_periodic_lnk_atoms/mdout.1NLN_MD_ntb1_aq1
qmmm2/1NLN_periodic_lnk_atoms/mdout.1NLN_MD_ntb1_aq2
qmmm2/1NLN_periodic_lnk_atoms/mdout.1NLN_MD_ntb1_aq2_NUMER_DERIV
qmmm2/1NLN_periodic_lnk_atoms/mdout.1NLN_MD_ntb1_lnk_dis_neg
qmmm2/1NLN_periodic_lnk_atoms/mdout.1NLN_MD_ntb1_lnk_method2
qmmm2/1NLN_periodic_lnk_atoms/mdout.1NLN_MD_ntb1_mmcorr
qmmm2/1NLN_periodic_lnk_atoms/mdout.1NLN_MD_ntb1_qmewald2
qmmm2/1NLN_periodic_lnk_atoms/mdout.1NLN_MD_ntb2
qmmm2/1NLN_periodic_lnk_atoms/mdout.1NLN_min
qmmm2/1NLN_test_diagonalizers/mdout.1NLN_auto
qmmm2/1NLN_test_diagonalizers/mdout.1NLN_dspev
qmmm2/1NLN_test_diagonalizers/mdout.1NLN_dspevd
qmmm2/1NLN_test_diagonalizers/mdout.1NLN_dspevx
qmmm2/1NLN_test_diagonalizers/mdout.1NLN_dsyev
qmmm2/1NLN_test_diagonalizers/mdout.1NLN_dsyevd
qmmm2/1NLN_test_diagonalizers/mdout.1NLN_dsyevr
qmmm2/1NLN_test_diagonalizers/mdout.1NLN_internal
qmmm2/crambin_2/crambin_md_calc_mulliken.out
qmmm2/crambin_2/crambin_md.out
qmmm2/crambin_2/crambin_md_qmgb2_alpb.out
qmmm2/crambin_2/crambin_md_qmgb2_aq1.out
qmmm2/crambin_2/crambin_md_qmgb2_aq2.out
qmmm2/crambin_2/crambin_md_qmgb2.out
qmmm2/crambin_2/crambin_md_qmgb2_saltcon.out
qmmm2/crambin_2/crambin.out
qmmm2/crambin/crambin_md_hot_start.out
qmmm2/crambin/crambin_md.out
qmmm2/crambin/crambin.out
qmmm2/crambin/mdcrd
qmmm2/crambin/mdvel
qmmm2/crambin_PM6/crambin_md.out
qmmm2/crambin_PM6/crambin.out
qmmm2/crambin_PM6/mdcrd
qmmm2/crambin_PM6/mdvel
qmmm2/crambin_PM6/restrt
qmmm2/crambin/restrt
qmmm2/input_validation/invalid_atom_ids.out
qmmm2/input_validation/non-unique.out
qmmm2/lysine_AM1/lysine_md.out
qmmm2/lysine_AM1/lysine.out
qmmm2/lysine_MNDO/lysine_md.out
qmmm2/lysine_MNDO/lysine.out
qmmm2/lysine_PM3_calc_dipole/lysine_md.out
qmmm2/lysine_PM3_calc_dipole/lysine.out
qmmm2/lysine_PM3_calc_mulliken/lysine_md.out
qmmm2/lysine_PM3_calc_mulliken/lysine.out
qmmm2/lysine_PM3/lysine_md_lnk_dis_neg.out
qmmm2/lysine_PM3/lysine_md_lnk_method_2.out
qmmm2/lysine_PM3/lysine_md.out
qmmm2/lysine_PM3/lysine_md_qmmm_int0.out
qmmm2/lysine_PM3/lysine_md_qmmm_int2.out
qmmm2/lysine_PM3/lysine.out
qmmm2/lysine_PM3_qmgb0/lysine_md.out
qmmm2/lysine_PM3_qmgb0/lysine.out
qmmm2/lysine_PM3_qmgb2_alpb/lysine_md.out
qmmm2/lysine_PM3_qmgb2/lysine_md_adjust_q1.out
qmmm2/lysine_PM3_qmgb2/lysine_md_adjust_q2.out
qmmm2/lysine_PM3_qmgb2/lysine_md_igb2.out
qmmm2/lysine_PM3_qmgb2/lysine_md_igb5.out
qmmm2/lysine_PM3_qmgb2/lysine_md_igb7.out
qmmm2/lysine_PM3_qmgb2/lysine_md_lnk_dis_neg.out
qmmm2/lysine_PM3_qmgb2/lysine_md.out
qmmm2/lysine_PM3_qmgb2/lysine.out
qmmm2/lysine_PM6/lysine_md.out
qmmm2/lysine_PM6/lysine.out
qmmm2/MG_QM_water_MM_AM1_periodic/mdout.imaged
qmmm2/MG_QM_water_MM_AM1_periodic/mdout.imaged_md
qmmm2/MG_QM_water_MM_AM1_periodic/mdout.img_center
qmmm2/MG_QM_water_MM_AM1_periodic/mdout.img_center_bigqmcut_md
qmmm2/MG_QM_water_MM_AM1_periodic/mdout.img_center_md
qmmm2/MG_QM_water_MM_AM1_periodic/mdout.notimaged
qmmm2/MG_QM_water_MM_AM1_periodic/mdout.notimaged_md
qmmm2/MG_QM_water_MM_AM1_periodic/mdout.notimaged_md_pme
qmmm2/MG_QM_water_MM_AM1_periodic/mdout.notimaged_md_pme_qmewald
qmmm2/MG_QM_water_MM_AM1_periodic/mdout.notimaged_md_pme_qmewald_lowmem
qmmm2/MG_QM_water_MM_AM1_qmcut_ADDMM/MG_QM_water_MM_MD.out
qmmm2/MG_QM_water_MM_AM1_qmcut_ADDMM/MG_QM_water_MM.out
qmmm2/MG_QM_water_MM_AM1_qmcut_lowmem/MG_QM_water_MM_MD.out
qmmm2/MG_QM_water_MM_AM1_qmcut/MG_QM_water_MM_MD.out
qmmm2/MG_QM_water_MM_AM1_qmcut/MG_QM_water_MM.out
qmmm2/PM3-MAIS/hcl_wat.mdcrd
qmmm2/PM3-MAIS/hcl_wat.mdout
qmmm2/PM3-MAIS/zundel.mdcrd
qmmm2/PM3-MAIS/zundel.mdout
qmmm2/PM3-MMX/ammonia_dimer.out
qmmm2/PM3-MMX/crambin_md_pm3mmx.out
qmmm2/PM3-MMX/formic_acid_dimer.out
qmmm2/PM3-MMX/water_dimer.out
qmmm2/PM3-MMX2/methanethiol_water.out
qmmm2/pure_QM_MD_AM1_ADDMM/nma_md.out
qmmm2/pure_QM_MD_AM1_ADDMM/nma.out
qmmm2/pure_QM_MD_AM1/C6H4FCL_md.out
qmmm2/pure_QM_MD_AM1/nma_md.out
qmmm2/pure_QM_MD_AM1/nma.out
qmmm2/pure_QM_MD/C6H4FCL_md.out
qmmm2/pure_QM_MD_MNDO/C6H4FCL_md.out
qmmm2/pure_QM_MD_MNDO/nma_md.out
qmmm2/pure_QM_MD_MNDO/nma.out
qmmm2/pure_QM_MD/nma_md_diag_routine_0.out
qmmm2/pure_QM_MD/nma_md_diag_routine_2.out
qmmm2/pure_QM_MD/nma_md_diag_routine_3.out
qmmm2/pure_QM_MD/nma_md_diag_routine_4.out
qmmm2/pure_QM_MD/nma_md_diag_routine_5.out
qmmm2/pure_QM_MD/nma_md_diag_routine_6.out
qmmm2/pure_QM_MD/nma_md_diag_routine_7.out
qmmm2/pure_QM_MD/nma_md.out
qmmm2/pure_QM_MD/nma_md_qmgb0.out
qmmm2/pure_QM_MD/nma_md_qmgb1.out
qmmm2/pure_QM_MD/nma_md_qmgb2.out
qmmm2/pure_QM_MD/nma_md_qmgb2_saltcon.out
qmmm2/pure_QM_MD/nma_md_qmgb3.out
qmmm2/pure_QM_MD/nma.out
qmmm2/pure_QM_MD_NUMER_DERIV/nma_md.out
qmmm2/pure_QM_MD_NUMER_DERIV/nma_md_qmgb0.out
qmmm2/pure_QM_MD_NUMER_DERIV/nma_md_qmgb2.out
qmmm2/pure_QM_MD_NUMER_DERIV/nma_md_qmgb2_saltcon.out
qmmm2/pure_QM_MD_NUMER_DERIV/nma.out
qmmm2/pure_QM_MD_PDDGMNDO/C6H4FCL_md.out
qmmm2/pure_QM_MD_PDDGMNDO/nma_md.out
qmmm2/pure_QM_MD_PDDGMNDO/nma.out
qmmm2/pure_QM_MD_PDDGPM3_08/nma_md.out
qmmm2/pure_QM_MD_PDDGPM3_08/nma.out
qmmm2/pure_QM_MD_PDDGPM3/C6H4FCL_md.out
qmmm2/pure_QM_MD_PDDGPM3/nma_md.out
qmmm2/pure_QM_MD_PDDGPM3/nma.out
qmmm2/pure_QM_MD_PM6/nma_md.out
qmmm2/pure_QM_MD_PM6/nma.out
qmmm2/pure_QM_MD_RM1/C6H4FCL_md.out
qmmm2/pure_QM_MD_RM1/nma_md.out
qmmm2/pure_QM_MD_RM1/nma.out
qmmm2/pure_QM_MD_shake/nma_md.out
qmmm2/pure_QM_MD_tight_p/nma_md.out
qmmm2/pure_QM_MD_tight_p/nma.out
qmmm2/tip3p_cap/tip3p_cap_md.out
qmmm2/tip3p_cap/tip3p_cap_md_shake.out
qmmm2/tip3p_cap/tip3p_cap_md_shake_qmshake_off.out
qmmm2/tip3p_cap/tip3p_cap.out
qmmm2/variable_solvent/mdout.1NLN_MD_ntb1_vsolv
qmmm2/variable_solvent/mg_periodic_vsolv_wat.out
qmmm2/xcrd_build_test/mdout.oct_nma_imaged
qmmm2/xcrd_build_test/mdout.oct_nma_noimage
qmmm2/xcrd_build_test/mdout.ortho_qmewald0
qmmm2/xcrd_build_test/mdout.truncoct_qmewald0
qmmm2/znme2/znme2.znb.md.out
qmmm2/znme2/znme2.znb.min.out
qmmm_DFTB/1NLN_periodic_lnk_atoms_DFTB/DISP.CHEK
qmmm_DFTB/1NLN_periodic_lnk_atoms_DFTB/mdout.1NLN_MD_ntb1
qmmm_DFTB/1NLN_periodic_lnk_atoms_DFTB/mdout.1NLN_MD_ntb1_aq1
qmmm_DFTB/1NLN_periodic_lnk_atoms_DFTB/mdout.1NLN_MD_ntb1_aq1_disp
qmmm_DFTB/1NLN_periodic_lnk_atoms_DFTB/mdout.1NLN_MD_ntb1_aq2
qmmm_DFTB/1NLN_periodic_lnk_atoms_DFTB/mdout.1NLN_MD_ntb1_lnk_dis_neg
qmmm_DFTB/1NLN_periodic_lnk_atoms_DFTB/mdout.1NLN_MD_ntb1_lnk_method2
qmmm_DFTB/1NLN_periodic_lnk_atoms_DFTB/mdout.1NLN_MD_ntb1_qmewald2
qmmm_DFTB/1NLN_periodic_lnk_atoms_DFTB/mdout.1NLN_MD_ntb2
qmmm_DFTB/1NLN_periodic_lnk_atoms_DFTB/mdout.1NLN_min
qmmm_DFTB/3rd-order/ala8/mdout_PA
qmmm_DFTB/3rd-order/ala8/mdout_PR
qmmm_DFTB/3rd-order/water/mdout
qmmm_DFTB/3rd-order/water/mdout.read_file
qmmm_DFTB/3rd-order/water/mdout.read_mdin
qmmm_DFTB/aladip_tip3p_ewaldpme/mdout.aladip_ewald_ntb1
qmmm_DFTB/aladip_tip3p_ewaldpme/mdout.aladip_ewald_ntb1_link_atoms
qmmm_DFTB/aladip_tip3p_ewaldpme/mdout.aladip_ewald_ntb1_qmewald2
qmmm_DFTB/aladip_tip3p_ewaldpme/mdout.aladip_ewald_ntb2
qmmm_DFTB/aladip_tip3p_ewaldpme/mdout.aladip_pme_ntb1
qmmm_DFTB/aladip_tip3p_ewaldpme/mdout.aladip_pme_ntb2
qmmm_DFTB/aladip_tip3p_ewaldpme/mdout.aladip_pme_ntb2_link_atoms
qmmm_DFTB/aladip_tip3p_ewaldpme/mdout.aladip_pme_ntb2_link_atoms_aq1
qmmm_DFTB/aladip_tip3p_ewaldpme/mdout.aladip_pme_ntb2_link_atoms_aq2
qmmm_DFTB/aladip_tip3p_ewaldpme/mdout.aladip_pme_ntb2_qmewald2
qmmm_DFTB/aladip_tip3p_ewaldpme/mdout.aladip_pme_ntb2_telec
qmmm_DFTB/crambin_2_DFTB/crambin_md_calc_mulliken.out
qmmm_DFTB/crambin_2_DFTB/crambin_md.out
qmmm_DFTB/crambin_2_DFTB/crambin_md_qmgb2_alpb.out
qmmm_DFTB/crambin_2_DFTB/crambin_md_qmgb2_aq1.out
qmmm_DFTB/crambin_2_DFTB/crambin_md_qmgb2_aq2.out
qmmm_DFTB/crambin_2_DFTB/crambin_md_qmgb2.out
qmmm_DFTB/crambin_2_DFTB/crambin_md_qmgb2_saltcon.out
qmmm_DFTB/crambin_2_DFTB/crambin.out
qmmm_DFTB/crambin_DFTB/crambin_md_hot_start.out
qmmm_DFTB/crambin_DFTB/crambin_md.out
qmmm_DFTB/crambin_DFTB/crambin.out
qmmm_DFTB/crambin_DFTB/mdcrd
qmmm_DFTB/crambin_DFTB/mdvel
qmmm_DFTB/crambin_DFTB/restrt
qmmm_DFTB/lysine_DFTB_calc_mulliken/lysine_md.out
qmmm_DFTB/lysine_DFTB_calc_mulliken/lysine.out
qmmm_DFTB/lysine_DFTB/lysine_md_lnk_dis_neg.out
qmmm_DFTB/lysine_DFTB/lysine_md_lnk_method2.out
qmmm_DFTB/lysine_DFTB/lysine_md.out
qmmm_DFTB/lysine_DFTB/lysine_md_qmmm_int0.out
qmmm_DFTB/lysine_DFTB/lysine.out
qmmm_DFTB/lysine_DFTB_qmgb0/lysine_md.out
qmmm_DFTB/lysine_DFTB_qmgb0/lysine.out
qmmm_DFTB/lysine_DFTB_qmgb2_alpb/lysine_md.out
qmmm_DFTB/lysine_DFTB_qmgb2/lysine_md_adjust_q1.out
qmmm_DFTB/lysine_DFTB_qmgb2/lysine_md_adjust_q2.out
qmmm_DFTB/lysine_DFTB_qmgb2/lysine_md_igb2.out
qmmm_DFTB/lysine_DFTB_qmgb2/lysine_md_igb5.out
qmmm_DFTB/lysine_DFTB_qmgb2/lysine_md_igb7.out
qmmm_DFTB/lysine_DFTB_qmgb2/lysine_md.out
qmmm_DFTB/lysine_DFTB_qmgb2/lysine.out
qmmm_DFTB/MG_QM_water_MM_DFTB_periodic/mdout.imaged
qmmm_DFTB/MG_QM_water_MM_DFTB_periodic/mdout.imaged_md
qmmm_DFTB/MG_QM_water_MM_DFTB_periodic/mdout.img_center
qmmm_DFTB/MG_QM_water_MM_DFTB_periodic/mdout.img_center_bigqmcut_md
qmmm_DFTB/MG_QM_water_MM_DFTB_periodic/mdout.img_center_md
qmmm_DFTB/MG_QM_water_MM_DFTB_periodic/mdout.notimaged
qmmm_DFTB/MG_QM_water_MM_DFTB_periodic/mdout.notimaged_md
qmmm_DFTB/MG_QM_water_MM_DFTB_periodic/mdout.notimaged_md_pme
qmmm_DFTB/MG_QM_water_MM_DFTB_periodic/mdout.notimaged_md_pme_qmewald
qmmm_DFTB/MG_QM_water_MM_DFTB_qmcut_lowmem/MG_QM_water_MM_MD.out
qmmm_DFTB/MG_QM_water_MM_DFTB_qmcut/MG_QM_water_MM_MD.out
qmmm_DFTB/MG_QM_water_MM_DFTB_qmcut/MG_QM_water_MM.out
qmmm_DFTB/pure_QM_MD_DFTB/DISP.CHEK
qmmm_DFTB/pure_QM_MD_DFTB/nma_disper.out
qmmm_DFTB/pure_QM_MD_DFTB/nma_md.out
qmmm_DFTB/pure_QM_MD_DFTB/nma_md_qmgb0.out
qmmm_DFTB/pure_QM_MD_DFTB/nma_md_qmgb1.out
qmmm_DFTB/pure_QM_MD_DFTB/nma_md_qmgb2.out
qmmm_DFTB/pure_QM_MD_DFTB/nma_md_qmgb2_saltcon.out
qmmm_DFTB/pure_QM_MD_DFTB/nma.out
qmmm_DFTB/pure_QM_MD_shake_DFTB/nma_md.out
qmmm_DFTB/pure_QM_MD_tight_p_DFTB/nma_md.out
qmmm_DFTB/pure_QM_MD_tight_p_DFTB/nma.out
qmmm_DFTB/tip3p_cap_DFTB/tip3p_cap_md.out
qmmm_DFTB/tip3p_cap_DFTB/tip3p_cap_md_shake.out
qmmm_DFTB/tip3p_cap_DFTB/tip3p_cap_md_shake_qmshake_off.out
qmmm_DFTB/tip3p_cap_DFTB/tip3p_cap.out
rdc/gcg.csa_min.o
rdc/gcg.csa.o
rdc/gcg.dip.o
rem_gb_2rep/rem.log
rem_gb_2rep/rem.out.000
rem_gb_2rep/rem.out.001
rem_gb_4rep/rem.log
rem_gb_4rep/rem.out.000
rem_gb_4rep/rem.out.001
rem_gb_4rep/rem.out.002
rem_gb_4rep/rem.out.003
rem_hybrid/rem.log
rem_hybrid/rem.out.000
rem_hybrid/rem.out.001
rem_wat/reminfo.000
rem_wat/reminfo.001
rem_wat/rem.log
rem_wat/rem.out.000
rem_wat/rem.out.001
rism3d/ala/ala.dist.out
rism3d/ala/ala.hnc.out
rism3d/ala/ala.out
rism3d/ala/ala.resize.out
rism3d/ala/cuv.H1.5.dx
rism3d/ala/cuv.O.5.dx
rism3d/ala/guv.H1.5.dx
rism3d/ala/guv.O.5.dx
rism3d/ala/huv.H1.5.dx
rism3d/ala/huv.O.5.dx
rism3d/phosphate/ph10-nacl.out
rism3d/phosphate/ph10.out
rism3d/phosphate/ph1-nacl.out
rism3d/phosphate/ph1.out
rism3d/phosphate/ph20.out
rism3d/phosphate/ph2.out
sander_pbsa_decpw/mdout.pbsa_decpw
sander_pbsa_decres/mdout.pbsa_decres
sander_pbsa_delphi/mdout.1az6.min
sander_pbsa_dmp/mdout.dmp.min
sander_pbsa_ipb2/mdout.110D.min
sander_pbsa_lpb/mdout.min_bc5_solv1
sander_pbsa_lpb/mdout.min_bc5_solv2
sander_pbsa_lpb/mdout.min_bc5_solv3
sander_pbsa_lpb/mdout.min_bc5_solv4
sander_pbsa_lpb/mdout.min_bc6_solv1
sander_pbsa_lpb/mdout.min_bc6_solv3
sander_pbsa_lpb/mdout.min_bc6_solv4
sander_pbsa_radi/alabk.out
sander_pbsa_radi/arg.out
sander_pbsa_radi/ash.out
sander_pbsa_radi/asn.out
sander_pbsa_radi/asp.out
sander_pbsa_radi/Br.out
sander_pbsa_radi/Ca.out
sander_pbsa_radi/Cl.out
sander_pbsa_radi/Cs.out
sander_pbsa_radi/cym.out
sander_pbsa_radi/cys.out
sander_pbsa_radi/cyx.out
sander_pbsa_radi/da3p.out
sander_pbsa_radi/da5p.out
sander_pbsa_radi/danp.out
sander_pbsa_radi/da.out
sander_pbsa_radi/dap.out
sander_pbsa_radi/dc.out
sander_pbsa_radi/dg.out
sander_pbsa_radi/dt.out
sander_pbsa_radi/F.out
sander_pbsa_radi/glh.out
sander_pbsa_radi/gln.out
sander_pbsa_radi/glu.out
sander_pbsa_radi/glybk.out
sander_pbsa_radi/hid.out
sander_pbsa_radi/hie.out
sander_pbsa_radi/hip.out
sander_pbsa_radi/ile.out
sander_pbsa_radi/IM.out
sander_pbsa_radi/I.out
sander_pbsa_radi/K.out
sander_pbsa_radi/leu.out
sander_pbsa_radi/Li.out
sander_pbsa_radi/lyn.out
sander_pbsa_radi/lys.out
sander_pbsa_radi/met.out
sander_pbsa_radi/MG.out
sander_pbsa_radi/Na.out
sander_pbsa_radi/nhe.out
sander_pbsa_radi/nma.out
sander_pbsa_radi/phe.out
sander_pbsa_radi/probk.out
sander_pbsa_radi/ra3p.out
sander_pbsa_radi/ra5p.out
sander_pbsa_radi/ranp.out
sander_pbsa_radi/rap.out
sander_pbsa_radi/Rb.out
sander_pbsa_radi/ru.out
sander_pbsa_radi/ser.out
sander_pbsa_radi/thr.out
sander_pbsa_radi/tp3.out
sander_pbsa_radi/trp.out
sander_pbsa_radi/tyr.out
sander_pbsa_radi/val.out
sander_pbsa_radi/Zn.out
sander_pbsa_tsr/mdout.tsrb.min
sodium/md1.o
softcore/complex/out.0
softcore/complex/out.1
softcore/complex/restrt.0
softcore/complex/restrt.1
softcore/complex_rst/out.0
softcore/complex_rst/out.1
softcore/complex_rst/restrt.0
softcore/complex_rst/restrt.1
softcore/dynlmb/out.0
softcore/dynlmb/out.1
softcore/dynlmb/restrt.0
softcore/dynlmb/restrt.1
softcore/electro/out.0
softcore/electro/out.1
softcore/electro/restrt.0
softcore/electro/restrt.1
softcore/min/out.0
softcore/min/out.1
softcore/min/restrt.0
softcore/min/restrt.1
softcore/short_md/out.0
softcore/short_md/out.1
softcore/short_md/out2.0
softcore/short_md/out2.1
softcore/short_md/restrt.0
softcore/short_md/restrt.1
softcore/short_md/restrt2.0
softcore/short_md/restrt2.1
tgtmd/change_target.ntr/tgtmd.out
tgtmd/change_target.rms/tgtmd.out
tgtmd/change_target/tgtmd.out
tgtmd/conserve_ene/tgtmd.out
tgtmd/minimize/tgtmin.out
tgtmd/PME/tgtmd.out
ti_decomp/ti_decomp_1.out
ti_decomp/ti_decomp_2.out
ti_eth2meth_gas/out.eth_ic1_k1_c0.5
ti_eth2meth_gas/out.eth_ic1_k1_c0.5.methane
ti_eth2meth_gas/out.eth_ic1_k6_c0.5
ti_eth2meth_gas/out.eth_ic1_k6_c0.5.methane
ti_ggcc/out_icfe1_klambda_1_clambda_0.5.p1
ti_ggcc/out_icfe1_klambda_1_clambda_0.5.p2
ti_ggcc/out_icfe1_klambda_6_clambda_0.5.p1
ti_mass/pentadiene/bead1.out
ti_mass/pentadiene/bead1.rst
ti_mass/pentadiene/bead2.out
ti_mass/pentadiene/bead2.rst
ti_mass/pentadiene/inf.1
ti_mass/pentadiene/inf.2
ti_mass/pentadiene/pimd.out
ti_mass/pent_LES_PIMD/.out
ti_mass/pent_LES_PIMD/mdinfo
ti_mass/pent_LES_PIMD/NHC.dat
ti_mass/pent_LES_PIMD/pent_les.crd
ti_mass/pent_LES_PIMD/pent-TI_les.top
ti_mass/pent_LES_PIMD/pimd.out
ti_mass/pent_LES_PIMD/restrt
tip4p/logfile
tip4p/mdout.tip4p
tip4p/mdout.tip4p_nve
tip5p/logfile
tip5p/mdout.tip5p
tip5p/mdout.tip5p_nve
trajene_box/mdcrd.out
trajene_box/trajene.out
trajene/mdcrd.out
trajene_netcdf/mdcrd.out.nc
trajene_netcdf/trajene.out
trajene/trajene.out
trx/logfile
trx/mdout.trx
trx/mdout.trx.cpln
trx/mdout.trx.cpln.pmemd
ubiquitin/mdcrd
ubiquitin/mden
ubiquitin/mdout.ubiquitin
ubiquitin/mdvel
ubiquitin/restrt
ubiquitin/rstdip
umbrella/chi_vs_t
umbrella/mdout.umbrella
variable_14/logfile
variable_14/variable_14_igb1.mdout
variable_14/variable_14_ntb1.mdout
"
echo $delete_list | xargs /bin/rm -f

# Remove cuda remd test output
cd cuda/remd && make clean && cd ../..

# Remove hip remd test output
cd hip/remd && make clean && cd ../..
