# Output of self.cfg.asdict() in easyblock.py.L2705 - horovod_v6
{
    'description': 'Horovod is a distributed training framework for TensorFlow.', 
    'homepage':'https://github.com/uber/horovod', 
    'name': 'Horovod', 
    'toolchain': {'name': 'foss', 'version': '2023a'}, 
    'version':'0.28.1', 
    'software_license': None, 
    'software_license_urls': None, 
    'docurls': None, 
    'onlytcmod': False,
    'toolchainopts': None, 
    'banned_linked_shared_libs': [], 
    'bitbucket_account': 'horovod', 
    'buildopts': '',
    'checksums': [], 
    'configopts': '', 
    'cuda_compute_capabilities': [], 
    'download_instructions': '', 
    'easyblock': 'PythonBundle', 
    'easybuild_version': None, 
    'enhance_sanity_check': False, 
    'fix_bash_shebang_for': None,
    'fix_perl_shebang_for': None, 
    'fix_python_shebang_for': None, 
    'github_account': 'horovod', 
    'hidden': False,
    'installopts': '', 
    'maxparallel': None, 
    'module_only': False, 
    'parallel': 8, 
    'patches': [], 
    'prebuildopts': '',
    'preconfigopts': '', 
    'preinstallopts': '', 
    'pretestopts': '', 
    'postinstallcmds': [], 
    'postinstallpatches': [],
    'postinstallmsgs': [], 
    'required_linked_shared_libs': [], 
    'runtest': True, 
    'bin_lib_subdirs': [],
    'sanity_check_commands': ['horovodrun --help'], 
    'sanity_check_paths': {
        'files': ['bin/horovodrun'], 
        'dirs': ['lib/python3.11/site-packages']
    }, 
    'skip': False, 
    'skipsteps': [], 
    'source_urls': ['https://pypi.python.org/packages/source/H/Horovod'], 
    'sources': [], 
    'stop': None, 
    'testopts': '', 
    'tests': [],
    'unpack_options': '', 
    'unwanted_env_vars': {}, 
    'versionprefix': '', 
    'versionsuffix': '-TensorFlow-2.13.0',
    'buildininstalldir': False, 
    'cleanupoldbuild': True, 
    'cleanupoldinstall': True, 
    'dontcreateinstalldir': False,
    'keeppreviousinstall': False, 
    'keepsymlinks': False, 
    'start_dir': None, 
    'allow_system_deps': [],
    'builddependencies': [{
        'full_mod_name': 'CMake/3.26.3-GCCcore-12.3.0', 
        'short_mod_name': 'CMake/3.26.3-GCCcore-12.3.0', 
        'name': 'CMake', 
        'version': '3.26.3', 
        'versionsuffix': '', 
        'toolchain': {'name': 'GCCcore', 'version': '12.3.0'}, 
        'toolchain_inherited': False, 
        'system': False, 
        'hidden': False, 
        'build_only': True, 
        'external_module': False, 
        'external_module_metadata': {}
    }], 
    'dependencies': [
        {
            'full_mod_name': 'Python/3.11.3-GCCcore-12.3.0', 
            'short_mod_name': 'Python/3.11.3-GCCcore-12.3.0', 
            'name': 'Python', 
            'version': '3.11.3', 
            'versionsuffix': '', 
            'toolchain': {'name': 'GCCcore', 'version': '12.3.0'}, 
            'toolchain_inherited': False,
            'system': False, 
            'hidden': False, 
            'build_only': False, 
            'external_module': False, 
            'external_module_metadata': {}
        },
        {
            'full_mod_name': 'PyYAML/6.0-GCCcore-12.3.0', 
            'short_mod_name': 'PyYAML/6.0-GCCcore-12.3.0', 
            'name': 'PyYAML',
            'version': '6.0', 
            'versionsuffix': '', 
            'toolchain': {'name': 'GCCcore', 'version': '12.3.0'},
            'toolchain_inherited': False, 
            'system': False, 
            'hidden': False, 
            'build_only': False, 
            'external_module': False,
            'external_module_metadata': {}
        }, 
        {
            'full_mod_name': 'TensorFlow/2.13.0-foss-2023a', 
            'short_mod_name': 'TensorFlow/2.13.0-foss-2023a', 
            'name': 'TensorFlow', 
            'version': '2.13.0', 
            'versionsuffix': '', 
            'toolchain': {'name': 'foss', 'version': '2023a'}, 
            'toolchain_inherited': False, 
            'system': False, 
            'hidden': False, 
            'build_only': False, 
            'external_module': False, 
            'external_module_metadata': {}
        }
    ], 
    'hiddendependencies': [], 
    'multi_deps': {},
    'multi_deps_load_default': True, 
    'osdependencies': [], 
    'moddependpaths': None, 
    'swapdependencies': [],
    'accept_eula': False, 
    'group': None, 
    'key': None, 
    'license_file': None, 
    'license_server': None,
    'license_server_port': None, 
    'exts_download_dep_fail': False, 
    'exts_classmap': {}, 
    'exts_defaultclass': 'PythonPackage', 
    'exts_default_options': {
        'buildcmd': None, 
        'check_ldshared': None, 
        'download_dep_fail': True,
        'install_src': None, 
        'install_target': 'install', 
        'pip_ignore_installed': True, 
        'pip_no_index': None,
        'pip_verbose': None, 
        'req_py_majver': None, 
        'req_py_minver': None, 
        'max_py_majver': None, 
        'max_py_minver': None,
        'sanity_pip_check': True, 
        'runtest': True, 
        'testinstall': False, 
        'unpack_sources': None, 
        'unversioned_packages': [], 
        'use_pip': True, 
        'use_pip_editable': False, 
        'use_pip_extras': None, 
        'use_pip_for_deps': False,
        'use_pip_requirement': False, 
        'zipped_egg': False, 
        'source_urls': ['https://pypi.python.org/packages/source/H/Horovod'], 
        'options': {}
    }, 
    'exts_filter': ('python -c "import %(ext_name)s"', ''), 
    'exts_list': [
        ('cloudpickle', '2.2.1', {
            'checksums': ['d89684b8de9e34a2a43b3460fbca07d09d6e25ce858df4d5a44240403b6178f5']
        }), 
        ('horovod', '0.28.1', {
            'preinstallopts': 'module swap protobuf/3.21.9-GCCcore-12.3.0 && HOROVOD_WITH_MPI=1 HOROVOD_WITH_TENSORFLOW=1 HOROVOD_WITHOUT_PYTORCH=1 HOROVOD_WITHOUT_MXNET=1 ', 
            'patches': ['Horovod-0.28.1_support_flatbuffers_2.0.6.patch'],
            'checksums': ['92a43f5a94c43907a56805bad15f19700c62ffc83b7ca483f9e104e229f67ef0', '9696ffb3b2bad1d6dd5a9f37bc58078ca7c585f933bcbec037036ad9fc0b297d']
        })
    ], 
    'allow_append_abs_path': False, 
    'allow_prepend_abs_path': False, 
    'include_modpath_extensions': True, 
    'modaliases': {}, 
    'modextrapaths': {},
    'modextrapaths_append': {}, 
    'modextravars': {},
    'modloadmsg': {}, 
    'modunloadmsg': {}, 
    'modluafooter': '',
    'modaltsoftname': None, 
    'modtclfooter': '', 
    'moduleclass': 'tools', 
    'moduleforceunload': False,
    'moduleloadnoconflict': False, 
    'module_depends_on': False, 
    'recursive_module_unload': None, 
    'citing': None,
    'docpaths': None, 
    'examples': None, 
    'site_contacts': None, 
    'upstream_contacts': None, 
    'usage': None, 
    'whatis':None, 
    'block': None, 
    'buildstats': None, 
    'deprecated': False, 
    'build_info_msg': None, 
    'altroot': None,
    'altversion': None, 
    'default_component_specs': {}, 
    'components': (), 
    'sanity_check_components': [],
    'sanity_check_all_components': False, 
    'default_easyblock': None, 
    'buildcmd': None, 
    'check_ldshared': None,
    'download_dep_fail': None, 
    'install_src': None, 
    'install_target': 'install', 
    'pip_ignore_installed': True,
    'pip_no_index': None, 
    'pip_verbose': None, 
    'req_py_majver': None, 
    'req_py_minver': None, 
    'max_py_majver': None,
    'max_py_minver': None, 
    'sanity_pip_check': True, 
    'testinstall': False, 
    'unpack_sources': None,
    'unversioned_packages': [], 
    'use_pip': True, 
    'use_pip_editable': False, 
    'use_pip_extras': None, 
    'use_pip_for_deps': False, 
    'use_pip_requirement': False, 
    'zipped_egg': False, 
    'options': {}, 
    'parsed': True
}