#! /usr/bin/env python
##
# Copyright 2020-2026 Ghent University
#
# This file is part of EasyBuild,
# originally created by the HPC team of Ghent University (http://ugent.be/hpc/en),
# with support of Ghent University (http://ugent.be/hpc),
# the Flemish Supercomputer Centre (VSC) (https://www.vscentrum.be),
# Flemish Research Foundation (FWO) (http://www.fwo.be/en)
# and the Department of Economy, Science and Innovation (EWI) (http://www.ewi-vlaanderen.be/en).
#
# https://github.com/easybuilders/easybuild
#
# EasyBuild is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation v2.
#
# EasyBuild is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with EasyBuild.  If not, see <http://www.gnu.org/licenses/>.
##

"""
EasyBuild support for building and installing 3D Slicer.

@author: Pavel Tomanek (Inuits/Ugent) with help of ChatGPT6
"""

import os
import shlex
import stat

from easybuild.easyblocks.generic.cmakemake import CMakeMake
from easybuild.tools.build_log import EasyBuildError
from easybuild.tools.filetools import adjust_permissions, copy_file, expand_glob_paths, extract_file
from easybuild.tools.filetools import find_glob_pattern, mkdir, symlink, write_file
from easybuild.tools.run import run_shell_cmd
from easybuild.tools.utilities import nub


class EB_Slicer(CMakeMake):
    """Support for building and installing 3D Slicer."""

    def _cpack_install(self):
        """Generate Slicer's CPack TGZ package and extract it."""
        if not self.separate_build_dir:
            raise EasyBuildError("Slicer requires a separate CMake build directory")

        slicer_build_dir = os.path.join(self.separate_build_dir, 'Slicer-build')
        cpack_dir = os.path.join(self.separate_build_dir, 'cpack-install')
        mkdir(cpack_dir, parents=True)

        cmd = "cpack --config CPackConfig.cmake -G TGZ -B %s" % shlex.quote(cpack_dir)
        run_shell_cmd(cmd, work_dir=slicer_build_dir)

        cpack_archive = find_glob_pattern(
            os.path.join(cpack_dir, 'Slicer-%s-*.tar.gz' % self.version)
        )

        # A plain CMake install is incomplete for Slicer's SuperBuild.
        # Extract the contents of Slicer's official CPack archive instead.
        extract_file(
            cpack_archive,
            self.installdir,
            extra_options='--strip-components=1',
            change_into_dir=False,
        )

    def _install_tbb_libraries(self):
        """Install TBB libraries built internally by Slicer's SuperBuild."""
        tbb_libdir = os.path.join(self.separate_build_dir, 'tbb-install', 'lib')
        target_libdir = os.path.join(self.installdir, 'lib')
        mkdir(target_libdir, parents=True)

        tbb_libs = expand_glob_paths([
            os.path.join(tbb_libdir, 'libtbb*.so*'),
        ])

        # Preserve the symlink layout generated by TBB rather than
        # dereferencing libtbb.so/libtbb.so.<major> links while copying.
        for src in tbb_libs:
            dst = os.path.join(target_libdir, os.path.basename(src))
            if os.path.islink(src):
                symlink(os.readlink(src), dst, use_abspath_source=False)
            else:
                copy_file(src, dst)

    def _fix_superbuild_rpaths(self):
        """Remove SuperBuild staging paths retained in packaged ELF files."""
        slicer_libdir = find_glob_pattern(
            os.path.join(self.installdir, 'lib', 'Slicer-*')
        )
        slicer_rel_rpath = '$ORIGIN/../lib/%s' % os.path.basename(slicer_libdir)

        stale_dcmtk = os.path.join(self.separate_build_dir, 'DCMTK-build', 'lib')
        stale_openjpeg = os.path.join(self.separate_build_dir, 'OpenJPEG-install', 'lib')

        patched = 0

        for dirpath, _dirnames, filenames in os.walk(self.installdir):
            for filename in filenames:
                path = os.path.join(dirpath, filename)

                # Match `find -type f`: do not patch through symlinks.
                if os.path.islink(path):
                    continue

                quoted_path = shlex.quote(path)

                res = run_shell_cmd(
                    "patchelf --print-rpath %s" % quoted_path,
                    fail_on_error=False,
                    hidden=True,
                )
                if res.exit_code != 0:
                    continue

                rpath = res.output.strip()
                if not rpath:
                    continue

                entries = rpath.split(':')
                changed = False

                if any(stale_dcmtk in entry for entry in entries):
                    entries = [entry for entry in entries if stale_dcmtk not in entry]
                    if slicer_rel_rpath not in entries:
                        entries.append(slicer_rel_rpath)
                    changed = True

                if any(stale_openjpeg in entry for entry in entries):
                    entries = [entry for entry in entries if stale_openjpeg not in entry]
                    changed = True

                if changed:
                    new_rpath = ':'.join(nub(entry for entry in entries if entry))
                    cmd = "patchelf --force-rpath --set-rpath %s %s" % (
                        shlex.quote(new_rpath),
                        quoted_path,
                    )
                    run_shell_cmd(cmd)
                    patched += 1

        self.log.info("Updated RPATH in %d installed Slicer ELF file(s)", patched)

    def _install_launcher_wrapper(self):
        """Install a Slicer wrapper that automatically loads the Biomedisa extension."""
        wrapper = """#!/bin/bash

SLICER_ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)
BIOMEDISA_EXT="$EBROOTBIOMEDISA/biomedisa_slicer_extension/biomedisa_extension"

exec "$SLICER_ROOT/Slicer" \\
    --additional-module-paths \\
    "$BIOMEDISA_EXT/SegmentEditorBiomedisa" \\
    "$BIOMEDISA_EXT/SegmentEditorBiomedisaPrediction" \\
    "$BIOMEDISA_EXT/SegmentEditorBiomedisaTraining" \\
    "$@"
"""

        wrapper_path = os.path.join(self.installdir, 'bin', 'Slicer')
        write_file(wrapper_path, wrapper)
        adjust_permissions(
            wrapper_path,
            stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH,
            add=True,
        )

    def install_step(self):
        """Install Slicer using its CPack-generated package."""
        self._cpack_install()
        self._install_tbb_libraries()
        self._fix_superbuild_rpaths()
        self._install_launcher_wrapper()

    def sanity_check_step(self):
        """Run Slicer-specific sanity checks."""
        custom_paths = {
            'files': [
                'Slicer',
                'bin/Slicer',
                'bin/SlicerApp-real',
            ],
            'dirs': [
                'lib/Slicer-%s' % '.'.join(self.version.split('.')[:2]),
            ],
        }

        headless = 'QT_QPA_PLATFORM=offscreen QT_QPA_OFFSCREEN_NO_GLX=1 '

        custom_commands = [
            '%s/Slicer --launcher-help' % self.installdir,
            headless + 'Slicer --no-splash --no-main-window --exit-after-startup',
            headless + 'Slicer --no-splash --no-main-window '
            '--python-code "import slicer, vtk, qt, ctk" --exit-after-startup',
            headless + 'Slicer --no-splash --no-main-window '
            '--python-code "mods = slicer.app.moduleManager().factoryManager().instantiatedModuleNames(); '
            'assert all(x in mods for x in [\'SegmentEditorBiomedisa\', '
            '\'SegmentEditorBiomedisaPrediction\', \'SegmentEditorBiomedisaTraining\'])" '
            '--exit-after-startup',
        ]

        super().sanity_check_step(
            custom_paths=custom_paths,
            custom_commands=custom_commands,
        )
