#!/usr/bin/env bash

set -euo pipefail

echo "============================================================"
echo "3D Slicer smoke test"
echo "============================================================"

# Locate the Slicer AppLauncher. Prefer EBROOTSLICER because the actual
# launcher is installed in the Slicer installation root rather than bin.
if [ "$#" -eq 1 ]; then
    SLICER="$1"
elif [ -n "${EBROOTSLICER:-}" ] && [ -x "$EBROOTSLICER/Slicer" ]; then
    SLICER="$EBROOTSLICER/Slicer"
elif command -v Slicer >/dev/null 2>&1; then
    SLICER=$(command -v Slicer)
else
    echo "ERROR: could not locate the Slicer launcher"
    echo "Load the Slicer module or pass the launcher path as argument."
    exit 1
fi

SLICER=$(readlink -f "$SLICER")
SLICER_ROOT=$(dirname "$SLICER")

echo "Slicer launcher: $SLICER"
echo "Slicer root:     $SLICER_ROOT"
echo

export QT_QPA_PLATFORM=offscreen
export QT_QPA_OFFSCREEN_NO_GLX=1

TMPDIR_SMOKE=$(mktemp -d)
trap 'rm -rf "$TMPDIR_SMOKE"' EXIT

pass()
{
    printf '[PASS] %s\n' "$1"
}

fail()
{
    printf '[FAIL] %s\n' "$1" >&2
    exit 1
}


# ----------------------------------------------------------------------
# 1. Basic AppLauncher test
# ----------------------------------------------------------------------

echo "--- AppLauncher ------------------------------------------------"

if "$SLICER" --help >/dev/null 2>&1; then
    pass "Slicer AppLauncher starts and --help works"
else
    fail "Slicer AppLauncher --help failed"
fi

VERSION=$("$SLICER" --version 2>&1 | head -n 1 || true)

if [ -n "$VERSION" ]; then
    echo "       $VERSION"
    pass "Slicer reports its version"
else
    fail "Slicer did not report a version"
fi


# ----------------------------------------------------------------------
# 2. Validate the environment generated by CTK AppLauncher
# ----------------------------------------------------------------------

echo
echo "--- AppLauncher environment ----------------------------------"

LAUNCHER_ENV=$(env -u LD_LIBRARY_PATH "$SLICER" --launcher-dump-environment)

LDLP=$(printf '%s\n' "$LAUNCHER_ENV" | sed -n 's/^LD_LIBRARY_PATH=//p')

if [ -n "$LDLP" ]; then
    pass "AppLauncher generates LD_LIBRARY_PATH"
else
    fail "AppLauncher did not generate LD_LIBRARY_PATH"
fi

FOUND_SLICER_LIB=0

while IFS= read -r path; do
    if [ -d "$path" ]; then
        path=$(readlink -f "$path")
        case "$path" in
            "$SLICER_ROOT"/lib/Slicer-*)
                FOUND_SLICER_LIB=1
                break
                ;;
        esac
    fi
done < <(printf '%s\n' "$LDLP" | tr ':' '\n')

if [ "$FOUND_SLICER_LIB" -eq 1 ]; then
    pass "AppLauncher includes Slicer's internal library directory"
else
    fail "Slicer's internal library directory is missing from launcher environment"
fi


# ----------------------------------------------------------------------
# 3. Embedded Python / Slicer / VTK / Qt / CTK / MRML test
# ----------------------------------------------------------------------

echo
echo "--- Slicer Python environment --------------------------------"

PYTEST="$TMPDIR_SMOKE/slicer_python_smoke.py"

cat > "$PYTEST" <<'PYEOF'
import os
import sys
import tempfile
import traceback

try:
    import slicer
    import vtk
    import qt
    import ctk

    import numpy
    import scipy
    import pydicom
    import requests
    import dicomweb_client
    from PIL import Image

    print(f"Python: {sys.version.split()[0]}")
    print(f"Slicer: {slicer.app.applicationVersion}")
    print(f"VTK:    {vtk.vtkVersion.GetVTKVersion()}")
    print(f"NumPy:  {numpy.__version__}")
    print(f"SciPy:  {scipy.__version__}")

    assert sys.version_info[:2] == (3, 13), \
        f"Unexpected Python version: {sys.version}"

    assert slicer.mrmlScene is not None
    assert hasattr(slicer, "vtkMRMLScalarVolumeNode")
    assert hasattr(vtk, "vtkImageData")
    assert hasattr(qt, "QObject")
    assert hasattr(ctk, "ctkDICOMDatabase")

    # Exercise VTK and MRML together.
    image = vtk.vtkImageData()
    image.SetDimensions(8, 7, 6)
    image.AllocateScalars(vtk.VTK_FLOAT, 1)
    image.GetPointData().GetScalars().Fill(42.0)

    volume = slicer.mrmlScene.AddNewNodeByClass(
        "vtkMRMLScalarVolumeNode",
        "EasyBuildSmokeTest",
    )
    assert volume is not None

    volume.SetAndObserveImageData(image)
    volume.CreateDefaultDisplayNodes()

    assert volume.GetImageData() is not None
    assert volume.GetImageData().GetDimensions() == (8, 7, 6)
    assert volume.GetImageData().GetScalarRange() == (42.0, 42.0)

    # Exercise Slicer's volume I/O.
    test_file = os.path.join(
        tempfile.gettempdir(),
        f"slicer-smoke-{os.getpid()}.nrrd",
    )

    try:
        assert slicer.util.saveNode(volume, test_file)
        assert os.path.isfile(test_file)

        slicer.mrmlScene.RemoveNode(volume)

        loaded = slicer.util.loadVolume(test_file)
        assert loaded is not None
        assert loaded.GetImageData() is not None
        assert loaded.GetImageData().GetDimensions() == (8, 7, 6)
        assert loaded.GetImageData().GetScalarRange() == (42.0, 42.0)

        slicer.mrmlScene.RemoveNode(loaded)
    finally:
        if os.path.exists(test_file):
            os.remove(test_file)

    # Check that important built-in modules were discovered.
    required_modules = (
        "volumes",
        "models",
        "transforms",
        "segmentations",
        "dicom",
    )

    for module_name in required_modules:
        module = getattr(slicer.modules, module_name, None)
        assert module is not None, \
            f"Slicer module was not discovered: {module_name}"

    print("Slicer Python/MRML/VTK/Qt/CTK smoke test passed")

except Exception:
    traceback.print_exc()
    sys.exit(1)

import gc

# Drop Python references to VTK/MRML objects before Slicer's shutdown
# leak check. Removing a node from the MRML scene does not destroy it
# while Python still owns a reference to the wrapped VTK object.
del loaded
del volume
del image

slicer.mrmlScene.Clear(0)
gc.collect()

slicer.util.exit(0)
PYEOF

if "$SLICER" \
    --no-splash \
    --no-main-window \
    --python-script "$PYTEST"; then
    pass "Embedded Python, VTK, Qt, CTK, MRML and volume I/O"
else
    fail "Slicer Python smoke test failed"
fi

# Creating and manipulating vtkMRMLScalarVolumeNode objects and using
# slicer.util.saveNode/loadVolume exercises Slicer's MRML and volume I/O
# APIs, rather than merely testing that the Python modules import.


# ----------------------------------------------------------------------
# 4. Launcher-aware linkage check
# ----------------------------------------------------------------------

echo
echo "--- ELF linkage ------------------------------------------------"

CHECKED=0
LINK_FAILURES=0

while IFS= read -r -d '' f; do
    if readelf -h "$f" >/dev/null 2>&1; then
        CHECKED=$((CHECKED + 1))

        set +e
        LDD_OUTPUT=$(env -u LD_LIBRARY_PATH LD_LIBRARY_PATH="$LDLP" \
            timeout 15s ldd "$f" 2>&1)
        LDD_RC=$?
        set -e

        if [ "$LDD_RC" -eq 124 ]; then
            echo "ERROR: ldd timed out for: $f"
            LINK_FAILURES=$((LINK_FAILURES + 1))
            continue
        fi

        MISSING=$(printf '%s\n' "$LDD_OUTPUT" | grep 'not found' || true)

        if [ -n "$MISSING" ]; then
            echo
            echo "Unresolved libraries in: $f"
            printf '%s\n' "$MISSING"
            LINK_FAILURES=$((LINK_FAILURES + 1))
        fi
    fi
done < <(
    find "$SLICER_ROOT" -type f \
        \( -perm /111 -o -name '*.so' -o -name '*.so.*' \) \
        -print0
)

echo "Checked $CHECKED ELF executables/libraries"

if [ "$CHECKED" -eq 0 ]; then
    fail "No ELF executables or libraries were checked"
fi

if [ "$LINK_FAILURES" -eq 0 ]; then
    pass "All installed ELF files resolve under the AppLauncher environment"
else
    fail "$LINK_FAILURES ELF file(s) have unresolved libraries"
fi


# ----------------------------------------------------------------------
# 5. Ensure no RPATH/RUNPATH points back into an EasyBuild build tree
# ----------------------------------------------------------------------

echo
echo "--- RPATH relocation ------------------------------------------"

BAD_RPATHS=0

while IFS= read -r -d '' f; do
    if readelf -h "$f" >/dev/null 2>&1; then
        RPATH=$(readelf -d "$f" 2>/dev/null |
            grep -E '\((RPATH|RUNPATH)\)' || true)

        if printf '%s\n' "$RPATH" |
            grep -Eq '/easybuild/build/Slicer/|/easybuild_obj/'; then
            echo
            echo "Build-tree RPATH/RUNPATH in: $f"
            printf '%s\n' "$RPATH"
            BAD_RPATHS=$((BAD_RPATHS + 1))
        fi
    fi
done < <(
    find "$SLICER_ROOT" -type f \
        \( -perm /111 -o -name '*.so' -o -name '*.so.*' \) \
        -print0
)

if [ "$BAD_RPATHS" -eq 0 ]; then
    pass "No installed ELF file contains a Slicer build-tree RPATH"
else
    fail "$BAD_RPATHS ELF file(s) contain build-tree RPATHs"
fi


echo
echo "============================================================"
echo "All Slicer smoke tests PASSED"
echo "============================================================"
