FROM rocker/r-ver:4.2.2

# Base packages
RUN apt -y update && \
    apt -y install wget vim mousepad && \
    apt -y install libx11-dev perl xterm cpanminus libxml2-dev libpng-dev

RUN mkdir /perl_modules
RUN cpanm -v -L /perl_modules local::lib@2.000029
RUN cpanm -v -L /perl_modules threads@2.21
RUN cpanm -v -L /perl_modules threads::shared@1.59
RUN cpanm -v -L /perl_modules Data::Dumper@2.183
RUN cpanm -v -L /perl_modules Log::Log4perl@1.54
RUN cpanm -v -L /perl_modules Module::Pluggable@5.2
RUN cpanm -v -L /perl_modules Log::Dispatch::FileRotate@1.38
RUN cpanm -v -L /perl_modules Config::Simple@4.58
RUN cpanm -v -L /perl_modules Text::Diff@1.45
RUN cpanm -v -L /perl_modules Text::Diff::HTML@0.08
RUN cpanm -v -L /perl_modules Text::Table@1.134
RUN cpanm -v -L /perl_modules Tk@804.035
RUN cpanm -v -L /perl_modules Tk::ItemStyle@4.004
RUN cpanm -v -L /perl_modules Tk::Pane@4.007
RUN cpanm -v -L /perl_modules Tk::Splashscreen@1.0
RUN cpanm -v -L /perl_modules --force Tk::JComboBox@1.14
RUN cpanm -v -L /perl_modules Tk::PlotDataset@2.05
RUN cpanm -v -L /perl_modules Tk::HdrResizeButton@1.5
RUN cpanm -v -L /perl_modules Net::EmptyPort
RUN cpanm -v -L /perl_modules File::Copy@2.35
RUN cpanm -v -L /perl_modules File::Copy::Recursive@0.45
RUN cpanm -v -L /perl_modules Crypt::CBC@2.33
RUN cpanm -v -L /perl_modules Crypt::Cipher::DES@0.072
RUN cpanm -v -L /perl_modules DBI@1.643
RUN cpanm -v -L /perl_modules DBD::SQLite@1.66
RUN cpanm -v -L /perl_modules Archive::Zip@1.68
RUN cpanm -v -L /perl_modules Image::Size@3.300
RUN cpanm -v -L /perl_modules XML::TreePP@0.43
RUN cpanm -v -L /perl_modules HTTP::Date@6.05
RUN cpanm -v -L /perl_modules Statistics::R@0.34
RUN cpanm -v -L /perl_modules Date::Parse@2.33
RUN cpanm -v -L /perl_modules Storable@3.15
RUN cpanm -v -L /perl_modules List::MoreUtils@0.430
RUN cpanm -v -L /perl_modules Test::Most@0.38
RUN cpanm -v -L /perl_modules Test::Files@0.15
# This one is not mentioned in the docs, but does seem necessary:
RUN cpanm -v -L /perl_modules Nice::Try@1.3.1

ENV PERL5LIB /perl_modules/lib/perl5
ENV PIRANA_LOCALLIB /perl_modules

# R package installations and their remaining OS dependencies
ARG REPO="https://certara.jfrog.io/artifactory/certara-cran-release-public/src/contrib"
COPY renv-R-4.2.2.lock renv.lock
RUN apt -y install \
        pkg-config libfontconfig1-dev libcurl4-openssl-dev libssh-dev libssl-dev \
        libharfbuzz-dev libfribidi-dev libcairo2-dev libtiff5-dev libjpeg-dev && \
    R -e 'install.packages("renv")' && \
    wget $REPO/Archive/Certara.NLME8/1.2.1/Certara.NLME8_1.2.1.tar.gz \
         $REPO/Archive/Certara.RsNLME/1.1.0/Certara.RsNLME_1.1.0.tar.gz \
         $REPO/Archive/Certara.RsNLME.ModelBuilder/1.1.0/Certara.RsNLME.ModelBuilder_1.1.0.tar.gz \
         $REPO/Archive/Certara.RsNLME.ModelExecutor/1.1.0/Certara.RsNLME.ModelExecutor_1.1.0.tar.gz \
         $REPO/Archive/Certara.Xpose.NLME/1.1.0/Certara.Xpose.NLME_1.1.0.tar.gz \
         $REPO/Certara.ModelResults_3.0.0.tar.gz \
         $REPO/Certara.shinyAce.NLME_1.0.0.tar.gz \
         $REPO/Certara.shinymeta.NLME_1.0.0.tar.gz && \
    R -e 'library(renv); renv::restore()' && \
    ln -s /usr/local/bin/R /usr/bin/R  # needed for Pirana

# Installing a PDF viewer
RUN apt -y install xdg-utils mupdf && xdg-mime default mupdf.desktop application/pdf

# Installing RStudio
RUN apt -y install libclang-dev libxkbcommon-x11-0 libnss3 ffmpeg libgbm1 libasound2 && \
    wget https://download1.rstudio.org/electron/jammy/amd64/rstudio-2024.04.2-764-amd64.deb && \
    dpkg -i rstudio-2024.04.2-764-amd64.deb
ENV LD_LIBRARY_PATH="/usr/lib/rstudio:${LD_LIBRARY_PATH}"

WORKDIR /
